/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  trailingSlash: false,
  async redirects() {
    return [
      // Redirect old number page URLs to new /sayi/X format (handles with and without trailing slash)
      { source: '/1li-carpim-tablosu/:path*', destination: '/sayi/1', permanent: true },
      { source: '/2li-carpim-tablosu/:path*', destination: '/sayi/2', permanent: true },
      { source: '/3li-carpim-tablosu/:path*', destination: '/sayi/3', permanent: true },
      { source: '/4li-carpim-tablosu/:path*', destination: '/sayi/4', permanent: true },
      { source: '/5li-carpim-tablosu/:path*', destination: '/sayi/5', permanent: true },
      { source: '/6li-carpim-tablosu/:path*', destination: '/sayi/6', permanent: true },
      { source: '/7li-carpim-tablosu/:path*', destination: '/sayi/7', permanent: true },
      { source: '/8li-carpim-tablosu/:path*', destination: '/sayi/8', permanent: true },
      { source: '/9li-carpim-tablosu/:path*', destination: '/sayi/9', permanent: true },
      { source: '/10li-carpim-tablosu/:path*', destination: '/sayi/10', permanent: true },
      { source: '/11li-carpim-tablosu/:path*', destination: '/sayi/11', permanent: true },
      { source: '/12-li-carpim-tablosu/:path*', destination: '/sayi/12', permanent: true },
      { source: '/13li-carpim-tablosu/:path*', destination: '/sayi/13', permanent: true },
      { source: '/14-li-carpim-tablosu/:path*', destination: '/sayi/14', permanent: true },
      { source: '/15-li-carpim-tablosu/:path*', destination: '/sayi/15', permanent: true },
      { source: '/16-li-carpim-tablosu/:path*', destination: '/sayi/16', permanent: true },
      { source: '/17li-carpim-tablosu/:path*', destination: '/sayi/17', permanent: true },
      { source: '/18li-carpim-tablosu/:path*', destination: '/sayi/18', permanent: true },
      { source: '/19-li-carpim-tablosu/:path*', destination: '/sayi/19', permanent: true },
      { source: '/20-li-carpim-tablosu/:path*', destination: '/sayi/20', permanent: true },
      { source: '/21-li-carpim-tablosu/:path*', destination: '/sayi/21', permanent: true },
      { source: '/22-li-carpim-tablosu/:path*', destination: '/sayi/22', permanent: true },
      { source: '/23-li-carpim-tablosu/:path*', destination: '/sayi/23', permanent: true },
      { source: '/24-li-carpim-tablosu/:path*', destination: '/sayi/24', permanent: true },
      { source: '/25li-carpim-tablosu/:path*', destination: '/sayi/25', permanent: true },
      { source: '/26-li-carpim-tablosu/:path*', destination: '/sayi/26', permanent: true },
      { source: '/27-li-carpim-tablosu/:path*', destination: '/sayi/27', permanent: true },
      { source: '/28-li-carpim-tablosu/:path*', destination: '/sayi/28', permanent: true },
      { source: '/29-li-carpim-tablosu/:path*', destination: '/sayi/29', permanent: true },
      { source: '/30-li-carpim-tablosu/:path*', destination: '/sayi/30', permanent: true },
      { source: '/31-ler-carpim-tablosu/:path*', destination: '/sayi/31', permanent: true },
      { source: '/32-ler-carpim-tablosu/:path*', destination: '/sayi/32', permanent: true },
      { source: '/33-ler-carpim-tablosu/:path*', destination: '/sayi/33', permanent: true },
      { source: '/34-ler-carpim-tablosu/:path*', destination: '/sayi/34', permanent: true },
      { source: '/35-ler-carpim-tablosu/:path*', destination: '/sayi/35', permanent: true },
      { source: '/36-ler-carpim-tablosu/:path*', destination: '/sayi/36', permanent: true },
      { source: '/37-ler-carpim-tablosu/:path*', destination: '/sayi/37', permanent: true },
      { source: '/38-ler-carpim-tablosu/:path*', destination: '/sayi/38', permanent: true },
      { source: '/39-ler-carpim-tablosu/:path*', destination: '/sayi/39', permanent: true },
      { source: '/40-ler-carpim-tablosu/:path*', destination: '/sayi/40', permanent: true },
      { source: '/41-ler-carpim-tablosu/:path*', destination: '/sayi/41', permanent: true },
      { source: '/42-ler-carpim-tablosu/:path*', destination: '/sayi/42', permanent: true },
      { source: '/43-ler-carpim-tablosu/:path*', destination: '/sayi/43', permanent: true },
      { source: '/44-ler-carpim-tablosu/:path*', destination: '/sayi/44', permanent: true },
      { source: '/45-ler-carpim-tablosu/:path*', destination: '/sayi/45', permanent: true },
      { source: '/46-ler-carpim-tablosu/:path*', destination: '/sayi/46', permanent: true },
      { source: '/47-ler-carpim-tablosu/:path*', destination: '/sayi/47', permanent: true },
      { source: '/48-ler-carpim-tablosu/:path*', destination: '/sayi/48', permanent: true },
      { source: '/49-ler-carpim-tablosu/:path*', destination: '/sayi/49', permanent: true },
      { source: '/50-ler-carpim-tablosu/:path*', destination: '/sayi/50', permanent: true },
      { source: '/51-ler-carpim-tablosu/:path*', destination: '/sayi/51', permanent: true },
      { source: '/52-ler-carpim-tablosu/:path*', destination: '/sayi/52', permanent: true },
      { source: '/53-ler-carpim-tablosu/:path*', destination: '/sayi/53', permanent: true },
      { source: '/54-ler-carpim-tablosu/:path*', destination: '/sayi/54', permanent: true },
      { source: '/55-ler-carpim-tablosu/:path*', destination: '/sayi/55', permanent: true },
      { source: '/56-ler-carpim-tablosu/:path*', destination: '/sayi/56', permanent: true },
      { source: '/57-ler-carpim-tablosu/:path*', destination: '/sayi/57', permanent: true },
      { source: '/58-ler-carpim-tablosu/:path*', destination: '/sayi/58', permanent: true },
      { source: '/59-ler-carpim-tablosu/:path*', destination: '/sayi/59', permanent: true },
      { source: '/60-ler-carpim-tablosu/:path*', destination: '/sayi/60', permanent: true },
      { source: '/61-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/61', permanent: true },
      { source: '/62-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/62', permanent: true },
      { source: '/63-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/63', permanent: true },
      { source: '/64-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/64', permanent: true },
      { source: '/65-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/65', permanent: true },
      { source: '/66-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/66', permanent: true },
      { source: '/67-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/67', permanent: true },
      { source: '/68-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/68', permanent: true },
      { source: '/69-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/69', permanent: true },
      { source: '/70-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/70', permanent: true },
      { source: '/71-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/71', permanent: true },
      { source: '/72-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/72', permanent: true },
      { source: '/73-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/73', permanent: true },
      { source: '/74-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/74', permanent: true },
      { source: '/75-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/75', permanent: true },
      { source: '/76-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/76', permanent: true },
      { source: '/77-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/77', permanent: true },
      { source: '/78-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/78', permanent: true },
      { source: '/79-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/79', permanent: true },
      { source: '/80-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/80', permanent: true },
      { source: '/81-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/81', permanent: true },
      { source: '/82-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/82', permanent: true },
      { source: '/83-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/83', permanent: true },
      { source: '/84-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/84', permanent: true },
      { source: '/85-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/85', permanent: true },
      { source: '/86-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/86', permanent: true },
      { source: '/87-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/87', permanent: true },
      { source: '/88-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/88', permanent: true },
      { source: '/89-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/89', permanent: true },
      { source: '/90-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/90', permanent: true },
      { source: '/91-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/91', permanent: true },
      { source: '/92-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/92', permanent: true },
      { source: '/93-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/93', permanent: true },
      { source: '/94-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/94', permanent: true },
      { source: '/95-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/95', permanent: true },
      { source: '/96-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/96', permanent: true },
      { source: '/97-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/97', permanent: true },
      { source: '/98-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/98', permanent: true },
      { source: '/99-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/99', permanent: true },
      { source: '/100-ler-carpim-tablosu-oyunlar-alistirmalar/:path*', destination: '/sayi/100', permanent: true },
      { source: '/sample-page/:path*', destination: '/', permanent: true },
      { source: '/learn-multiplication/for-students', destination: '/ogrenciler-icin', permanent: true },
      { source: '/learn-multiplication/for-parents', destination: '/veliler-icin', permanent: true },
      { source: '/learn-multiplication/for-teachers', destination: '/ogretmenler-icin', permanent: true },
      
      // Redirect incorrect "to" format URLs to correct "-" format
      { source: '/1-to-10/:path*', destination: '/1-10', permanent: true },
      { source: '/11-to-20/:path*', destination: '/11-20', permanent: true },
      { source: '/21-to-30/:path*', destination: '/21-30', permanent: true },
      { source: '/31-to-40/:path*', destination: '/31-40', permanent: true },
      { source: '/41-to-50/:path*', destination: '/41-50', permanent: true },
      { source: '/51-to-60/:path*', destination: '/51-60', permanent: true },
      { source: '/61-to-70/:path*', destination: '/61-70', permanent: true },
      { source: '/71-to-80/:path*', destination: '/71-80', permanent: true },
      { source: '/81-to-90/:path*', destination: '/81-90', permanent: true },
      { source: '/91-to-100/:path*', destination: '/91-100', permanent: true },
      
      // Redirect old WordPress PDF URLs to relevant number pages
      { source: '/wp-content/uploads/2025/01/50-tablosu3.pdf', destination: '/sayi/50', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-58-3-683x1024-1.pdf', destination: '/sayi/58', permanent: true },
      { source: '/wp-content/uploads/2025/01/44-tablosu.pdf', destination: '/sayi/44', permanent: true },
      { source: '/wp-content/uploads/2024/12/4li-Carpim-Tablosu-512x1024-1.pdf', destination: '/sayi/4', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-96-2-683x1024-1.pdf', destination: '/sayi/96', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-61-2-683x1024-1.pdf', destination: '/sayi/61', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-90-683x1024-1.pdf', destination: '/sayi/90', permanent: true },
      { source: '/wp-content/uploads/2024/11/4-ler-Carpim-Tablosu.pdf', destination: '/sayi/4', permanent: true },
      { source: '/wp-content/uploads/2025/01/18li-Carpim-Tablosu2-512x1024-1.pdf', destination: '/sayi/18', permanent: true },
      { source: '/wp-content/uploads/2024/11/40ler-carpim-tablosu-pdf-3.pdf', destination: '/sayi/40', permanent: true },
      { source: '/wp-content/uploads/2025/01/1li-Carpim-Tablosu-1.pdf', destination: '/sayi/1', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-76-683x1024-1.pdf', destination: '/sayi/76', permanent: true },
      { source: '/wp-content/uploads/2025/01/29li-Carpim-Tablosu2-512x1024-1.pdf', destination: '/sayi/29', permanent: true },
      { source: '/wp-content/uploads/2025/01/11li-Carpim-Tablosu2-512x1024-1.pdf', destination: '/sayi/11', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-93-683x1024-1.pdf', destination: '/sayi/93', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-88-683x1024-1.pdf', destination: '/sayi/88', permanent: true },
      { source: '/wp-content/uploads/2025/01/45-tablosu3.pdf', destination: '/sayi/45', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-59-3-683x1024-1.pdf', destination: '/sayi/59', permanent: true },
      { source: '/wp-content/uploads/2024/11/40ler-carpim-tablosu-pdf-1.pdf', destination: '/sayi/40', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-96-683x1024-1.pdf', destination: '/sayi/96', permanent: true },
      { source: '/wp-content/uploads/2025/01/33-ler-carpim-2.pdf', destination: '/sayi/33', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-90-3-683x1024-1.pdf', destination: '/sayi/90', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-55-2-683x1024-1.pdf', destination: '/sayi/55', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-71-683x1024-1.pdf', destination: '/sayi/71', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-100-2-683x1024-1.pdf', destination: '/sayi/100', permanent: true },
      { source: '/wp-content/uploads/2025/01/26li-Carpim-Tablosu1-512x1024-1.pdf', destination: '/sayi/26', permanent: true },
      { source: '/wp-content/uploads/2025/01/43-tablosu2.pdf', destination: '/sayi/43', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-63-3-683x1024-1.pdf', destination: '/sayi/63', permanent: true },
      { source: '/wp-content/uploads/2025/01/1li-Carpim-Tablosu2-3.pdf', destination: '/sayi/1', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-53-3-683x1024-1.pdf', destination: '/sayi/53', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-52-683x1024-1.pdf', destination: '/sayi/52', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-55-683x1024-1.pdf', destination: '/sayi/55', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-87-2-683x1024-1.pdf', destination: '/sayi/87', permanent: true },
      { source: '/wp-content/uploads/2025/01/Carpim-Tablosu-65-683x1024-1.pdf', destination: '/sayi/65', permanent: true },
      { source: '/wp-content/uploads/2025/01/11li-Carpim-Tablosu-512x1024-1.pdf', destination: '/sayi/11', permanent: true },
      { source: '/wp-content/uploads/2025/01/37-tablosu-1.pdf', destination: '/sayi/37', permanent: true },
      
      // Redirect WordPress and malformed URLs to homepage
      { source: '/wp-content/:path*', destination: '/', permanent: true },
      { source: '/wp-includes/:path*', destination: '/', permanent: true },
      { source: '/wp-admin/:path*', destination: '/', permanent: true },
      { source: '/sayi/:slug(.*%7B.*)', destination: '/', permanent: true },
    ];
  },
}

module.exports = nextConfig
