# Translate German NumberPage.tsx to French
$ErrorActionPreference = "Stop"

Write-Host "Translating NumberPage.tsx from German to French..." -ForegroundColor Cyan

$file = Get-Content "app\components\fr\NumberPage.tsx" -Raw -Encoding UTF8

# Fix import
$file = $file -replace "import NumberGames from '\.\./NumberGames'","import NumberGames from './NumberGames'"

# Basic UI elements
$file = $file -replace 'Einmaleins-Tabelle von','Table de multiplication de'
$file = $file -replace 'Drucken','Imprimer'
$file = $file -replace 'Übungen','Exercices'
$file = $file -replace 'Spiele','Jeux'
$file = $file -replace 'Zurück zu','Retour à'
$file = $file -replace 'Bereich','Plage'
$file = $file -replace 'Multiplikationstabelle','Table de Multiplication'
$file = $file -replace 'Vollständige Multiplikationstabelle von','Table de multiplication complète de'
$file = $file -replace 'Was bedeutet mit','Que signifie multiplier par'
$file = $file -replace 'multiplizieren\?','?'
$file = $file -replace 'Warum ist es wichtig','Pourquoi est-il important'
$file = $file -replace 'Muster in der','Modèles dans la table de'
$file = $file -replace 'Tabelle','multiplication de'
$file = $file -replace 'Häufige Fehler','Erreurs courantes'
$file = $file -replace 'und wie man sie vermeidet','et comment les éviter'
$file = $file -replace 'Lerntipps für','Conseils d''apprentissage pour'
$file = $file -replace 'Multiplikationstabelle','la table de'
$file = $file -replace 'Regelmäßige Übung','Pratique régulière'
$file = $file -replace 'Visuelle Hilfsmittel','Aides visuelles'
$file = $file -replace 'Auswendiglernen','Mémorisation'
$file = $file -replace 'Mehr Übungsmöglichkeiten','Plus d''options de pratique'

# German verb forms to French
$file = $file -replace ' ist ein besonderer Fall',' est un cas spécial'
$file = $file -replace ' bedeutet','signifie'
$file = $file -replace ' hilft','aide'
$file = $file -replace ' entwickelt','développe'
$file = $file -replace ' erfordert','requiert'
$file = $file -replace ' verwendet','utilise'
$file = $file -replace ' hat','a'
$file = $file -replace ' schafft','crée'
$file = $file -replace ' zeigt','montre'
$file = $file -replace ' stärkt','renforce'
$file = $file -replace ' bildet','forme'
$file = $file -replace ' bringt','apporte'
$file = $file -replace ' macht','rend'
$file = $file -replace ' gibt','donne'

# Common German words to French
$file = $file -replace 'Gruppen','groupes'
$file = $file -replace 'Mal','fois'
$file = $file -replace 'Zahl','nombre'
$file = $file -replace 'Zahlen','nombres'
$file = $file -replace 'Ergebnis','résultat'
$file = $file -replace 'Ergebnisse','résultats'
$file = $file -replace 'Muster','modèle'
$file = $file -replace 'Eigenschaft','propriété'
$file = $file -replace 'gerade','pair'
$file = $file -replace 'ungerade','impair'
$file = $file -replace 'Addition','addition'
$file = $file -replace 'Subtraktion','soustraction'
$file = $file -replace 'Division','division'
$file = $file -replace 'Multiplikation','multiplication'
$file = $file -replace 'verdoppeln','doubler'
$file = $file -replace 'halbieren','diviser par deux'
$file = $file -replace 'Grundlage für','base pour'
$file = $file -replace 'im täglichen Leben','dans la vie quotidienne'
$file = $file -replace 'mathematisches Denken','pensée mathématique'
$file = $file -replace 'wiederholte Addition','addition répétée'
$file = $file -replace 'Lernspiele','jeux d''apprentissage'
$file = $file -replace 'Übungsaufgaben','exercices de pratique'
$file = $file -replace 'zum Ausdrucken','à imprimer'

# More specific phrases
$file = $file -replace 'Die Multiplikation mit','La multiplication par'
$file = $file -replace 'Wenn du','Lorsque vous'
$file = $file -replace 'eine Zahl','un nombre'
$file = $file -replace 'multiplizierst','multipliez'
$file = $file -replace 'das Ergebnis','le résultat'
$file = $file -replace 'immer','toujours'
$file = $file -replace 'dieselbe Zahl','le même nombre'
$file = $file -replace 'Dies wird','Cela s''appelle'
$file = $file -replace 'genannt','appelé'
$file = $file -replace 'Identitätseigenschaft','propriété d''identité'
$file = $file -replace 'Denke daran','Pensez-y'
$file = $file -replace 'wie','comme'
$file = $file -replace 'Wie viele','Combien de'
$file = $file -replace 'habe ich','ai-je'
$file = $file -replace 'nur','seulement'
$file = $file -replace 'genau','exactement'
$file = $file -replace 'was du','ce que vous'
$file = $file -replace 'angefangen hast','avez commencé'
$file = $file -replace 'praktisch','pratique'
$file = $file -replace 'weil','parce que'
$file = $file -replace 'häufig','souvent'
$file = $file -replace 'müssen','devons'
$file = $file -replace 'Dinge','choses'
$file = $file -replace 'zum Beispiel','par exemple'
$file = $file -replace 'Schuhe','chaussures'
$file = $file -replace 'Fahrradräder','roues de vélo'
$file = $file -replace 'oder','ou'
$file = $file -replace 'zwischen','entre'
$file = $file -replace 'zwei Personen','deux personnes'
$file = $file -replace 'gerecht teilen','partager équitablement'
$file = $file -replace 'sich selbst','lui-même'
$file = $file -replace 'hinzufügen','ajouter'
$file = $file -replace 'dreimal','trois fois'
$file = $file -replace 'kannst denken','pouvez penser'
$file = $file -replace 'als','comme'
$file = $file -replace 'diese Tabelle','cette table'
$file = $file -replace 'ist entscheidend','est essentielle'
$file = $file -replace 'für das Verständnis von','pour comprendre'
$file = $file -replace 'Dreiecken','triangles'
$file = $file -replace 'Trios','trios'
$file = $file -replace 'und alles','et tout'
$file = $file -replace 'was','ce qui'
$file = $file -replace 'in Dreiergruppen kommt','vient en groupes de trois'

# Fix encoding
$file = $file -replace 'Ã ','à'
$file = $file -replace 'Ã©','é'
$file = $file -replace 'Ã¨','è'
$file = $file -replace 'Ã§','ç'

$file | Set-Content "app\components\fr\NumberPage.tsx" -Encoding UTF8 -NoNewline

Write-Host "NumberPage.tsx translated to French!" -ForegroundColor Green
