// Finnish metadata for number pages (1-100)

export const numberTitlesFi: Record<number, string> = {
  1: 'Kertotaulu 1',
  2: 'Kertotaulu 2',
  3: 'Kertotaulu 3',
  4: 'Kertotaulu 4',
  5: 'Kertotaulu 5',
  6: 'Kertotaulu 6',
  7: 'Kertotaulu 7',
  8: 'Kertotaulu 8',
  9: 'Kertotaulu 9',
  10: 'Kertotaulu 10',
  11: 'Kertotaulu 11',
  12: 'Kertotaulu 12',
  13: 'Kertotaulu 13',
  14: 'Kertotaulu 14',
  15: 'Kertotaulu 15',
  16: 'Kertotaulu 16',
  17: 'Kertotaulu 17',
  18: 'Kertotaulu 18',
  19: 'Kertotaulu 19',
  20: 'Kertotaulu 20',
  21: 'Kertotaulu 21',
  22: 'Kertotaulu 22',
  23: 'Kertotaulu 23',
  24: 'Kertotaulu 24',
  25: 'Kertotaulu 25',
  26: 'Kertotaulu 26',
  27: 'Kertotaulu 27',
  28: 'Kertotaulu 28',
  29: 'Kertotaulu 29',
  30: 'Kertotaulu 30',
  31: 'Kertotaulu 31',
  32: 'Kertotaulu 32',
  33: 'Kertotaulu 33',
  34: 'Kertotaulu 34',
  35: 'Kertotaulu 35',
  36: 'Kertotaulu 36',
  37: 'Kertotaulu 37',
  38: 'Kertotaulu 38',
  39: 'Kertotaulu 39',
  40: 'Kertotaulu 40',
  41: 'Kertotaulu 41',
  42: 'Kertotaulu 42',
  43: 'Kertotaulu 43',
  44: 'Kertotaulu 44',
  45: 'Kertotaulu 45',
  46: 'Kertotaulu 46',
  47: 'Kertotaulu 47',
  48: 'Kertotaulu 48',
  49: 'Kertotaulu 49',
  50: 'Kertotaulu 50',
  51: 'Kertotaulu 51',
  52: 'Kertotaulu 52',
  53: 'Kertotaulu 53',
  54: 'Kertotaulu 54',
  55: 'Kertotaulu 55',
  56: 'Kertotaulu 56',
  57: 'Kertotaulu 57',
  58: 'Kertotaulu 58',
  59: 'Kertotaulu 59',
  60: 'Kertotaulu 60',
  61: 'Kertotaulu 61',
  62: 'Kertotaulu 62',
  63: 'Kertotaulu 63',
  64: 'Kertotaulu 64',
  65: 'Kertotaulu 65',
  66: 'Kertotaulu 66',
  67: 'Kertotaulu 67',
  68: 'Kertotaulu 68',
  69: 'Kertotaulu 69',
  70: 'Kertotaulu 70',
  71: 'Kertotaulu 71',
  72: 'Kertotaulu 72',
  73: 'Kertotaulu 73',
  74: 'Kertotaulu 74',
  75: 'Kertotaulu 75',
  76: 'Kertotaulu 76',
  77: 'Kertotaulu 77',
  78: 'Kertotaulu 78',
  79: 'Kertotaulu 79',
  80: 'Kertotaulu 80',
  81: 'Kertotaulu 81',
  82: 'Kertotaulu 82',
  83: 'Kertotaulu 83',
  84: 'Kertotaulu 84',
  85: 'Kertotaulu 85',
  86: 'Kertotaulu 86',
  87: 'Kertotaulu 87',
  88: 'Kertotaulu 88',
  89: 'Kertotaulu 89',
  90: 'Kertotaulu 90',
  91: 'Kertotaulu 91',
  92: 'Kertotaulu 92',
  93: 'Kertotaulu 93',
  94: 'Kertotaulu 94',
  95: 'Kertotaulu 95',
  96: 'Kertotaulu 96',
  97: 'Kertotaulu 97',
  98: 'Kertotaulu 98',
  99: 'Kertotaulu 99',
  100: 'Kertotaulu 100',
}

export const numberDescriptionsFi: Record<number, string> = {
  1: 'Hallitse kertotaulu 1. Selkeät selitykset, kuviot ja käytännön strategiat ymmärtääksesi ykkösen ominaisuuden ja kertolaskun perusteet.',
  2: 'Hallitse kertotaulu 2. Selkeät selitykset, kaksinkertaistamisen kuviot ja käytännön strategiat kertolaskun oppimiseen kahdella.',
  3: 'Hallitse kertotaulu 3. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  4: 'Hallitse kertotaulu 4. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  5: 'Hallitse kertotaulu 5. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  6: 'Hallitse kertotaulu 6. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  7: 'Hallitse kertotaulu 7. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  8: 'Hallitse kertotaulu 8. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  9: 'Hallitse kertotaulu 9. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  10: 'Hallitse kertotaulu 10. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  11: 'Hallitse kertotaulu 11. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  12: 'Hallitse kertotaulu 12. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  13: 'Hallitse kertotaulu 13. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  14: 'Hallitse kertotaulu 14. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  15: 'Hallitse kertotaulu 15. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  16: 'Hallitse kertotaulu 16. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  17: 'Hallitse kertotaulu 17. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  18: 'Hallitse kertotaulu 18. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  19: 'Hallitse kertotaulu 19. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  20: 'Hallitse kertotaulu 20. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  21: 'Hallitse kertotaulu 21. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  22: 'Hallitse kertotaulu 22. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  23: 'Hallitse kertotaulu 23. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  24: 'Hallitse kertotaulu 24. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  25: 'Hallitse kertotaulu 25. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  26: 'Hallitse kertotaulu 26. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  27: 'Hallitse kertotaulu 27. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  28: 'Hallitse kertotaulu 28. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  29: 'Hallitse kertotaulu 29. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  30: 'Hallitse kertotaulu 30. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  31: 'Hallitse kertotaulu 31. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  32: 'Hallitse kertotaulu 32. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  33: 'Hallitse kertotaulu 33. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  34: 'Hallitse kertotaulu 34. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  35: 'Hallitse kertotaulu 35. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  36: 'Hallitse kertotaulu 36. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  37: 'Hallitse kertotaulu 37. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  38: 'Hallitse kertotaulu 38. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  39: 'Hallitse kertotaulu 39. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  40: 'Hallitse kertotaulu 40. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  41: 'Hallitse kertotaulu 41. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  42: 'Hallitse kertotaulu 42. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  43: 'Hallitse kertotaulu 43. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  44: 'Hallitse kertotaulu 44. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  45: 'Hallitse kertotaulu 45. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  46: 'Hallitse kertotaulu 46. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  47: 'Hallitse kertotaulu 47. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  48: 'Hallitse kertotaulu 48. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  49: 'Hallitse kertotaulu 49. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  50: 'Hallitse kertotaulu 50. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  51: 'Hallitse kertotaulu 51. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  52: 'Hallitse kertotaulu 52. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  53: 'Hallitse kertotaulu 53. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  54: 'Hallitse kertotaulu 54. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  55: 'Hallitse kertotaulu 55. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  56: 'Hallitse kertotaulu 56. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  57: 'Hallitse kertotaulu 57. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  58: 'Hallitse kertotaulu 58. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  59: 'Hallitse kertotaulu 59. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  60: 'Hallitse kertotaulu 60. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  61: 'Hallitse kertotaulu 61. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  62: 'Hallitse kertotaulu 62. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  63: 'Hallitse kertotaulu 63. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  64: 'Hallitse kertotaulu 64. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  65: 'Hallitse kertotaulu 65. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  66: 'Hallitse kertotaulu 66. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  67: 'Hallitse kertotaulu 67. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  68: 'Hallitse kertotaulu 68. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  69: 'Hallitse kertotaulu 69. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  70: 'Hallitse kertotaulu 70. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  71: 'Hallitse kertotaulu 71. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  72: 'Hallitse kertotaulu 72. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  73: 'Hallitse kertotaulu 73. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  74: 'Hallitse kertotaulu 74. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  75: 'Hallitse kertotaulu 75. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  76: 'Hallitse kertotaulu 76. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  77: 'Hallitse kertotaulu 77. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  78: 'Hallitse kertotaulu 78. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  79: 'Hallitse kertotaulu 79. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  80: 'Hallitse kertotaulu 80. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  81: 'Hallitse kertotaulu 81. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  82: 'Hallitse kertotaulu 82. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  83: 'Hallitse kertotaulu 83. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  84: 'Hallitse kertotaulu 84. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  85: 'Hallitse kertotaulu 85. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  86: 'Hallitse kertotaulu 86. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  87: 'Hallitse kertotaulu 87. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  88: 'Hallitse kertotaulu 88. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  89: 'Hallitse kertotaulu 89. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  90: 'Hallitse kertotaulu 90. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  91: 'Hallitse kertotaulu 91. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  92: 'Hallitse kertotaulu 92. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  93: 'Hallitse kertotaulu 93. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  94: 'Hallitse kertotaulu 94. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  95: 'Hallitse kertotaulu 95. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  96: 'Hallitse kertotaulu 96. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  97: 'Hallitse kertotaulu 97. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  98: 'Hallitse kertotaulu 98. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  99: 'Hallitse kertotaulu 99. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
  100: 'Hallitse kertotaulu 100. Selkeät selitykset, kuviot ja käytännön strategiat harjoitteluun.',
}

export const numberSpecialPropertiesFi: Record<number, string> = {
  1: 'Mikä tahansa luku kerrottuna 1:llä on se itse',
  2: 'Pienin alkuluku, parillinen luku',
  3: 'Pienin pariton alkuluku',
  4: 'Parillinen luku, neliöluku (2×2)',
  5: 'Pyöristys ja kymmenykset, 50% = puolet',
  6: 'Parillinen luku, täydellinen luku',
  7: 'Pariton luku, alkuluku',
  8: 'Parillinen luku, kuutioluku (2³)',
  9: 'Pariton luku, neliöluku (3×3)',
  10: 'Kymmenjärjestelmän perusta',
  11: 'Pariton luku, alkuluku, palindromikuvio',
  12: 'Parillinen luku, erittäin yhdistetty luku',
  13: 'Pariton luku, alkuluku',
  14: 'Parillinen luku, 2×7',
  15: 'Pariton luku, 3×5',
  16: 'Parillinen luku, neliöluku (4×4)',
  17: 'Pariton luku, alkuluku',
  18: 'Parillinen luku, 2×9',
  19: 'Pariton luku, alkuluku',
  20: 'Parillinen luku, 2×10',
  21: 'Pariton luku, 3×7',
  22: 'Parillinen luku, 2×11',
  23: 'Pariton luku, alkuluku',
  24: 'Parillinen luku, erittäin yhdistetty luku',
  25: 'Pariton luku, neliöluku (5×5)',
  26: 'Parillinen luku, 2×13',
  27: 'Pariton luku, kuutioluku (3³)',
  28: 'Parillinen luku, täydellinen luku',
  29: 'Pariton luku, alkuluku',
  30: 'Parillinen luku, 3×10',
  31: 'Pariton luku, alkuluku',
  32: 'Parillinen luku, 2⁵',
  33: 'Pariton luku, 3×11',
  34: 'Parillinen luku, 2×17',
  35: 'Pariton luku, 5×7',
  36: 'Parillinen luku, neliöluku (6×6)',
  37: 'Pariton luku, alkuluku',
  38: 'Parillinen luku, 2×19',
  39: 'Pariton luku, 3×13',
  40: 'Parillinen luku, 4×10',
  41: 'Pariton luku, alkuluku',
  42: 'Parillinen luku, 6×7',
  43: 'Pariton luku, alkuluku',
  44: 'Parillinen luku, 4×11',
  45: 'Pariton luku, 5×9',
  46: 'Parillinen luku, 2×23',
  47: 'Pariton luku, alkuluku',
  48: 'Parillinen luku, erittäin yhdistetty luku',
  49: 'Pariton luku, neliöluku (7×7)',
  50: 'Parillinen luku, puolet sadasta',
  51: 'Pariton luku, 3×17',
  52: 'Parillinen luku, 4×13',
  53: 'Pariton luku, alkuluku',
  54: 'Parillinen luku, 6×9',
  55: 'Pariton luku, 5×11',
  56: 'Parillinen luku, 7×8',
  57: 'Pariton luku, 3×19',
  58: 'Parillinen luku, 2×29',
  59: 'Pariton luku, alkuluku',
  60: 'Parillinen luku, erittäin yhdistetty luku',
  61: 'Pariton luku, alkuluku',
  62: 'Parillinen luku, 2×31',
  63: 'Pariton luku, 7×9',
  64: 'Parillinen luku, neliöluku (8×8), kuutioluku (4³)',
  65: 'Pariton luku, 5×13',
  66: 'Parillinen luku, 6×11',
  67: 'Pariton luku, alkuluku',
  68: 'Parillinen luku, 4×17',
  69: 'Pariton luku, 3×23',
  70: 'Parillinen luku, 7×10',
  71: 'Pariton luku, alkuluku',
  72: 'Parillinen luku, erittäin yhdistetty luku',
  73: 'Pariton luku, alkuluku',
  74: 'Parillinen luku, 2×37',
  75: 'Pariton luku, 3×25',
  76: 'Parillinen luku, 4×19',
  77: 'Pariton luku, 7×11',
  78: 'Parillinen luku, 6×13',
  79: 'Pariton luku, alkuluku',
  80: 'Parillinen luku, 8×10',
  81: 'Pariton luku, neliöluku (9×9)',
  82: 'Parillinen luku, 2×41',
  83: 'Pariton luku, alkuluku',
  84: 'Parillinen luku, 7×12',
  85: 'Pariton luku, 5×17',
  86: 'Parillinen luku, 2×43',
  87: 'Pariton luku, 3×29',
  88: 'Parillinen luku, 8×11',
  89: 'Pariton luku, alkuluku',
  90: 'Parillinen luku, 9×10',
  91: 'Pariton luku, 7×13',
  92: 'Parillinen luku, 4×23',
  93: 'Pariton luku, 3×31',
  94: 'Parillinen luku, 2×47',
  95: 'Pariton luku, 5×19',
  96: 'Parillinen luku, erittäin yhdistetty luku',
  97: 'Pariton luku, alkuluku',
  98: 'Parillinen luku, 2×49',
  99: 'Pariton luku, 9×11',
  100: 'Parillinen luku, neliöluku (10×10), tärkeä virstanpylväs',
}
