export const numberTitlesPl: Record<number, string> = {
  1: "Tabliczka Mnożenia 1 | Ucz się mnożyć przez 1",
  2: "Tabliczka Mnożenia 2 | Ucz się mnożyć przez 2",
  3: "Tabliczka Mnożenia 3 | Ucz się mnożyć przez 3",
  4: "Tabliczka Mnożenia 4 | Ucz się mnożyć przez 4",
  5: "Tabliczka Mnożenia 5 | Ucz się mnożyć przez 5",
  6: "Tabliczka Mnożenia 6 | Ucz się mnożyć przez 6",
  7: "Tabliczka Mnożenia 7 | Ucz się mnożyć przez 7",
  8: "Tabliczka Mnożenia 8 | Ucz się mnożyć przez 8",
  9: "Tabliczka Mnożenia 9 | Ucz się mnożyć przez 9",
  10: "Tabliczka Mnożenia 10 | Ucz się mnożyć przez 10",
  11: "Tabliczka Mnożenia 11 | Ucz się mnożyć przez 11",
  12: "Tabliczka Mnożenia 12 | Ucz się mnożyć przez 12",
  13: "Tabliczka Mnożenia 13 | Ucz się mnożyć przez 13",
  14: "Tabliczka Mnożenia 14 | Ucz się mnożyć przez 14",
  15: "Tabliczka Mnożenia 15 | Ucz się mnożyć przez 15",
  16: "Tabliczka Mnożenia 16 | Ucz się mnożyć przez 16",
  17: "Tabliczka Mnożenia 17 | Ucz się mnożyć przez 17",
  18: "Tabliczka Mnożenia 18 | Ucz się mnożyć przez 18",
  19: "Tabliczka Mnożenia 19 | Ucz się mnożyć przez 19",
  20: "Tabliczka Mnożenia 20 | Ucz się mnożyć przez 20",
  21: "Tabliczka Mnożenia 21 | Ucz się mnożyć przez 21",
  22: "Tabliczka Mnożenia 22 | Ucz się mnożyć przez 22",
  23: "Tabliczka Mnożenia 23 | Ucz się mnożyć przez 23",
  24: "Tabliczka Mnożenia 24 | Ucz się mnożyć przez 24",
  25: "Tabliczka Mnożenia 25 | Ucz się mnożyć przez 25",
  26: "Tabliczka Mnożenia 26 | Ucz się mnożyć przez 26",
  27: "Tabliczka Mnożenia 27 | Ucz się mnożyć przez 27",
  28: "Tabliczka Mnożenia 28 | Ucz się mnożyć przez 28",
  29: "Tabliczka Mnożenia 29 | Ucz się mnożyć przez 29",
  30: "Tabliczka Mnożenia 30 | Ucz się mnożyć przez 30",
  31: "Tabliczka Mnożenia 31 | Ucz się mnożyć przez 31",
  32: "Tabliczka Mnożenia 32 | Ucz się mnożyć przez 32",
  33: "Tabliczka Mnożenia 33 | Ucz się mnożyć przez 33",
  34: "Tabliczka Mnożenia 34 | Ucz się mnożyć przez 34",
  35: "Tabliczka Mnożenia 35 | Ucz się mnożyć przez 35",
  36: "Tabliczka Mnożenia 36 | Ucz się mnożyć przez 36",
  37: "Tabliczka Mnożenia 37 | Ucz się mnożyć przez 37",
  38: "Tabliczka Mnożenia 38 | Ucz się mnożyć przez 38",
  39: "Tabliczka Mnożenia 39 | Ucz się mnożyć przez 39",
  40: "Tabliczka Mnożenia 40 | Ucz się mnożyć przez 40",
  41: "Tabliczka Mnożenia 41 | Ucz się mnożyć przez 41",
  42: "Tabliczka Mnożenia 42 | Ucz się mnożyć przez 42",
  43: "Tabliczka Mnożenia 43 | Ucz się mnożyć przez 43",
  44: "Tabliczka Mnożenia 44 | Ucz się mnożyć przez 44",
  45: "Tabliczka Mnożenia 45 | Ucz się mnożyć przez 45",
  46: "Tabliczka Mnożenia 46 | Ucz się mnożyć przez 46",
  47: "Tabliczka Mnożenia 47 | Ucz się mnożyć przez 47",
  48: "Tabliczka Mnożenia 48 | Ucz się mnożyć przez 48",
  49: "Tabliczka Mnożenia 49 | Ucz się mnożyć przez 49",
  50: "Tabliczka Mnożenia 50 | Ucz się mnożyć przez 50",
  51: "Tabliczka Mnożenia 51 | Ucz się mnożyć przez 51",
  52: "Tabliczka Mnożenia 52 | Ucz się mnożyć przez 52",
  53: "Tabliczka Mnożenia 53 | Ucz się mnożyć przez 53",
  54: "Tabliczka Mnożenia 54 | Ucz się mnożyć przez 54",
  55: "Tabliczka Mnożenia 55 | Ucz się mnożyć przez 55",
  56: "Tabliczka Mnożenia 56 | Ucz się mnożyć przez 56",
  57: "Tabliczka Mnożenia 57 | Ucz się mnożyć przez 57",
  58: "Tabliczka Mnożenia 58 | Ucz się mnożyć przez 58",
  59: "Tabliczka Mnożenia 59 | Ucz się mnożyć przez 59",
  60: "Tabliczka Mnożenia 60 | Ucz się mnożyć przez 60",
  61: "Tabliczka Mnożenia 61 | Ucz się mnożyć przez 61",
  62: "Tabliczka Mnożenia 62 | Ucz się mnożyć przez 62",
  63: "Tabliczka Mnożenia 63 | Ucz się mnożyć przez 63",
  64: "Tabliczka Mnożenia 64 | Ucz się mnożyć przez 64",
  65: "Tabliczka Mnożenia 65 | Ucz się mnożyć przez 65",
  66: "Tabliczka Mnożenia 66 | Ucz się mnożyć przez 66",
  67: "Tabliczka Mnożenia 67 | Ucz się mnożyć przez 67",
  68: "Tabliczka Mnożenia 68 | Ucz się mnożyć przez 68",
  69: "Tabliczka Mnożenia 69 | Ucz się mnożyć przez 69",
  70: "Tabliczka Mnożenia 70 | Ucz się mnożyć przez 70",
  71: "Tabliczka Mnożenia 71 | Ucz się mnożyć przez 71",
  72: "Tabliczka Mnożenia 72 | Ucz się mnożyć przez 72",
  73: "Tabliczka Mnożenia 73 | Ucz się mnożyć przez 73",
  74: "Tabliczka Mnożenia 74 | Ucz się mnożyć przez 74",
  75: "Tabliczka Mnożenia 75 | Ucz się mnożyć przez 75",
  76: "Tabliczka Mnożenia 76 | Ucz się mnożyć przez 76",
  77: "Tabliczka Mnożenia 77 | Ucz się mnożyć przez 77",
  78: "Tabliczka Mnożenia 78 | Ucz się mnożyć przez 78",
  79: "Tabliczka Mnożenia 79 | Ucz się mnożyć przez 79",
  80: "Tabliczka Mnożenia 80 | Ucz się mnożyć przez 80",
  81: "Tabliczka Mnożenia 81 | Ucz się mnożyć przez 81",
  82: "Tabliczka Mnożenia 82 | Ucz się mnożyć przez 82",
  83: "Tabliczka Mnożenia 83 | Ucz się mnożyć przez 83",
  84: "Tabliczka Mnożenia 84 | Ucz się mnożyć przez 84",
  85: "Tabliczka Mnożenia 85 | Ucz się mnożyć przez 85",
  86: "Tabliczka Mnożenia 86 | Ucz się mnożyć przez 86",
  87: "Tabliczka Mnożenia 87 | Ucz się mnożyć przez 87",
  88: "Tabliczka Mnożenia 88 | Ucz się mnożyć przez 88",
  89: "Tabliczka Mnożenia 89 | Ucz się mnożyć przez 89",
  90: "Tabliczka Mnożenia 90 | Ucz się mnożyć przez 90",
  91: "Tabliczka Mnożenia 91 | Ucz się mnożyć przez 91",
  92: "Tabliczka Mnożenia 92 | Ucz się mnożyć przez 92",
  93: "Tabliczka Mnożenia 93 | Ucz się mnożyć przez 93",
  94: "Tabliczka Mnożenia 94 | Ucz się mnożyć przez 94",
  95: "Tabliczka Mnożenia 95 | Ucz się mnożyć przez 95",
  96: "Tabliczka Mnożenia 96 | Ucz się mnożyć przez 96",
  97: "Tabliczka Mnożenia 97 | Ucz się mnożyć przez 97",
  98: "Tabliczka Mnożenia 98 | Ucz się mnożyć przez 98",
  99: "Tabliczka Mnożenia 99 | Ucz się mnożyć przez 99",
  100: "Tabliczka Mnożenia 100 | Ucz się mnożyć przez 100",
}

export const numberDescriptionsPl: Record<number, string> = {
  1: "Tabliczka mnożenia 1: Podstawowa właściwość tożsamości. Dowolna liczba pomnożona przez 1 pozostaje taka sama. Idealna dla początkujących do nauki podstaw mnożenia.",
  2: "Tabliczka mnożenia 2: Ucz się podwajać liczby. Mnożenie przez 2 oznacza dodanie liczby do samej siebie. Doskonała do rozwijania podstawowych umiejętności mnożenia.",
  3: "Tabliczka mnożenia 3: Dodaj liczbę trzy razy. Tabliczka 3 ma piękne wzory cyfr i jest doskonałą pierwszą prawdziwą wyzwaniem w nauce.",
  4: "Tabliczka mnożenia 4: Podwajaj dwukrotnie! Ponieważ 4 = 2 × 2, możesz podwoić liczbę, a następnie podwoić wynik ponownie. Łatwiejsza nauka, gdy znasz tabliczkę 2.",
  5: "Tabliczka mnożenia 5: Łatwy wzór - wszystkie wyniki kończą się na 0 lub 5. Idealna do nauki liczenia pieniędzy i czytania zegara. Jedna z najprostszych tabliczek.",
  6: "Tabliczka mnożenia 6: Pierwsza prawdziwa tabliczka. 6 = 2 × 3, więc możesz pomnożyć przez 2, a następnie przez 3. Ważna dla zaawansowanego mnożenia.",
  7: "Tabliczka mnożenia 7: Wyzwanie! Liczba 7 jest liczbą pierwszą i wymaga regularnej praktyki. Opanowanie jej zwiększa pewność siebie w matematyce.",
  8: "Tabliczka mnożenia 8: Podwajaj trzykrotnie (8 = 2 × 2 × 2). Gdy znasz dobrze tabliczki 2 i 4, ta staje się łatwiejsza. Ważna dla geometrii i muzyki.",
  9: "Tabliczka mnożenia 9: Fascynujące wzory! Suma cyfr w wynikach zawsze dzieli się przez 9. Istnieją również triki z palcami do nauki tej tabliczki.",
  10: "Tabliczka mnożenia 10: Najłatwiejsza! Po prostu dodaj zero na końcu. Podstawa naszego systemu dziesiętnego i punkt odniesienia dla wszystkich tabliczek.",
}

// Add generic descriptions for numbers 11-100
for (let i = 11; i <= 100; i++) {
  numberDescriptionsPl[i] = `Tabliczka mnożenia ${i}: Ucz się mnożyć przez ${i} z interaktywnymi ćwiczeniami, grami i materiałami do druku. Opanuj tabliczkę ${i} dzięki regularnej praktyce i zabawnym metodom nauki.`
}

export const numberSpecialPropertiesPl: Record<number, string> = {
  1: "Właściwość tożsamości",
  2: "Podwajanie",
  3: "Grupowanie po trójkach",
  4: "Podwójne podwojenie",
  5: "Kończy się na 0 lub 5",
  6: "Doskonała liczba",
  7: "Szczęśliwa siódemka",
  8: "Potęga dwójki (2³)",
  9: "Wzór sumy cyfr",
  10: "Właściwość podstawy",
}

export const numberKeywordsPl: Record<number, string[]> = {
  1: ["tabliczka mnożenia 1", "nauka mnożenia", "podstawy mnożenia", "właściwość tożsamości", "mnożenie dla początkujących"],
  2: ["tabliczka mnożenia 2", "podwajanie liczb", "liczby parzyste", "nauka po 2", "podstawowa tabliczka"],
  3: ["tabliczka mnożenia 3", "trójki", "wzór 3-6-9", "nauka po 3", "mnożenie przez trzy"],
  4: ["tabliczka mnożenia 4", "dwukrotne podwajanie", "mnożenie przez cztery", "kwadrat 2", "nauka po 4"],
  5: ["tabliczka mnożenia 5", "nauka po 5", "końce na 0 i 5", "mnożenie przez pięć", "tabliczka do zegara"],
  6: ["tabliczka mnożenia 6", "mnożenie przez sześć", "2×3", "doskonała liczba", "nauka po 6"],
  7: ["tabliczka mnożenia 7", "mnożenie przez siedem", "liczba pierwsza", "trudna tabliczka", "sztuczki z siódemkami"],
  8: ["tabliczka mnożenia 8", "mnożenie przez osiem", "potęga dwójki", "podwajanie 4", "tabliczka 8"],
  9: ["tabliczka mnożenia 9", "mnożenie przez dziewięć", "trik z palcami", "wzór cyfr", "sztuczka z 9"],
  10: ["tabliczka mnożenia 10", "mnożenie przez dziesięć", "dodaj zero", "system dziesiętny", "podstawa 10"],
}

// Add generic keywords for numbers 11-100
for (let i = 11; i <= 100; i++) {
  numberKeywordsPl[i] = [
    `tabliczka mnożenia ${i}`,
    `mnożenie przez ${i}`,
    `nauka tabliczki ${i}`,
    `ćwiczenia z mnożenia ${i}`,
    `tabliczki mnożenia`
  ]
}

export const focusKeywordPl = 'tabliczki mnożenia'
