// French metadata for number pages (1-100)

export const numberTitlesFr: Record<number, string> = {
  1: 'Table de Multiplication de 1 - Exercices',
  2: 'Table de Multiplication de 2 - Exercices',
  3: 'Table de Multiplication de 3 - Exercices',
  4: 'Table de Multiplication de 4 - Exercices',
  5: 'Table de Multiplication de 5 - Exercices',
  6: 'Table de Multiplication de 6 - Exercices',
  7: 'Table de Multiplication de 7 - Exercices',
  8: 'Table de Multiplication de 8 - Exercices',
  9: 'Table de Multiplication de 9 - Exercices',
  10: 'Table de Multiplication de 10 - Exercices',
  11: 'Table de Multiplication de 11 - Exercices',
  12: 'Table de Multiplication de 12 - Exercices',
  13: 'Table de Multiplication de 13 - Exercices',
  14: 'Table de Multiplication de 14 - Exercices',
  15: 'Table de Multiplication de 15 - Exercices',
  16: 'Table de Multiplication de 16 - Exercices',
  17: 'Table de Multiplication de 17 - Exercices',
  18: 'Table de Multiplication de 18 - Exercices',
  19: 'Table de Multiplication de 19 - Exercices',
  20: 'Table de Multiplication de 20 - Exercices',
  21: 'Table de Multiplication de 21 - Exercices',
  22: 'Table de Multiplication de 22 - Exercices',
  23: 'Table de Multiplication de 23 - Exercices',
  24: 'Table de Multiplication de 24 - Exercices',
  25: 'Table de Multiplication de 25 - Exercices',
  26: 'Table de Multiplication de 26 - Exercices',
  27: 'Table de Multiplication de 27 - Exercices',
  28: 'Table de Multiplication de 28 - Exercices',
  29: 'Table de Multiplication de 29 - Exercices',
  30: 'Table de Multiplication de 30 - Exercices',
  31: 'Table de Multiplication de 31 - Exercices',
  32: 'Table de Multiplication de 32 - Exercices',
  33: 'Table de Multiplication de 33 - Exercices',
  34: 'Table de Multiplication de 34 - Exercices',
  35: 'Table de Multiplication de 35 - Exercices',
  36: 'Table de Multiplication de 36 - Exercices',
  37: 'Table de Multiplication de 37 - Exercices',
  38: 'Table de Multiplication de 38 - Exercices',
  39: 'Table de Multiplication de 39 - Exercices',
  40: 'Table de Multiplication de 40 - Exercices',
  41: 'Table de Multiplication de 41 - Exercices',
  42: 'Table de Multiplication de 42 - Exercices',
  43: 'Table de Multiplication de 43 - Exercices',
  44: 'Table de Multiplication de 44 - Exercices',
  45: 'Table de Multiplication de 45 - Exercices',
  46: 'Table de Multiplication de 46 - Exercices',
  47: 'Table de Multiplication de 47 - Exercices',
  48: 'Table de Multiplication de 48 - Exercices',
  49: 'Table de Multiplication de 49 - Exercices',
  50: 'Table de Multiplication de 50 - Exercices',
  51: 'Table de Multiplication de 51 - Exercices',
  52: 'Table de Multiplication de 52 - Exercices',
  53: 'Table de Multiplication de 53 - Exercices',
  54: 'Table de Multiplication de 54 - Exercices',
  55: 'Table de Multiplication de 55 - Exercices',
  56: 'Table de Multiplication de 56 - Exercices',
  57: 'Table de Multiplication de 57 - Exercices',
  58: 'Table de Multiplication de 58 - Exercices',
  59: 'Table de Multiplication de 59 - Exercices',
  60: 'Table de Multiplication de 60 - Exercices',
  61: 'Table de Multiplication de 61 - Exercices',
  62: 'Table de Multiplication de 62 - Exercices',
  63: 'Table de Multiplication de 63 - Exercices',
  64: 'Table de Multiplication de 64 - Exercices',
  65: 'Table de Multiplication de 65 - Exercices',
  66: 'Table de Multiplication de 66 - Exercices',
  67: 'Table de Multiplication de 67 - Exercices',
  68: 'Table de Multiplication de 68 - Exercices',
  69: 'Table de Multiplication de 69 - Exercices',
  70: 'Table de Multiplication de 70 - Exercices',
  71: 'Table de Multiplication de 71 - Exercices',
  72: 'Table de Multiplication de 72 - Exercices',
  73: 'Table de Multiplication de 73 - Exercices',
  74: 'Table de Multiplication de 74 - Exercices',
  75: 'Table de Multiplication de 75 - Exercices',
  76: 'Table de Multiplication de 76 - Exercices',
  77: 'Table de Multiplication de 77 - Exercices',
  78: 'Table de Multiplication de 78 - Exercices',
  79: 'Table de Multiplication de 79 - Exercices',
  80: 'Table de Multiplication de 80 - Exercices',
  81: 'Table de Multiplication de 81 - Exercices',
  82: 'Table de Multiplication de 82 - Exercices',
  83: 'Table de Multiplication de 83 - Exercices',
  84: 'Table de Multiplication de 84 - Exercices',
  85: 'Table de Multiplication de 85 - Exercices',
  86: 'Table de Multiplication de 86 - Exercices',
  87: 'Table de Multiplication de 87 - Exercices',
  88: 'Table de Multiplication de 88 - Exercices',
  89: 'Table de Multiplication de 89 - Exercices',
  90: 'Table de Multiplication de 90 - Exercices',
  91: 'Table de Multiplication de 91 - Exercices',
  92: 'Table de Multiplication de 92 - Exercices',
  93: 'Table de Multiplication de 93 - Exercices',
  94: 'Table de Multiplication de 94 - Exercices',
  95: 'Table de Multiplication de 95 - Exercices',
  96: 'Table de Multiplication de 96 - Exercices',
  97: 'Table de Multiplication de 97 - Exercices',
  98: 'Table de Multiplication de 98 - Exercices',
  99: 'Table de Multiplication de 99 - Exercices',
  100: 'Table de Multiplication de 100 - Exercices',
}

export const numberDescriptionsFr: Record<number, string> = {
  1: 'Maîtrisez la table de 1. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  2: 'Maîtrisez la table de 2. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  3: 'Maîtrisez la table de 3. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  4: 'Maîtrisez la table de 4. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  5: 'Maîtrisez la table de 5. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  6: 'Maîtrisez la table de 6. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  7: 'Maîtrisez la table de 7. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  8: 'Maîtrisez la table de 8. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  9: 'Maîtrisez la table de 9. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  10: 'Maîtrisez la table de 10. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  11: 'Maîtrisez la table de 11. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  12: 'Maîtrisez la table de 12. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  13: 'Maîtrisez la table de 13. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  14: 'Maîtrisez la table de 14. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  15: 'Maîtrisez la table de 15. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  16: 'Maîtrisez la table de 16. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  17: 'Maîtrisez la table de 17. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  18: 'Maîtrisez la table de 18. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  19: 'Maîtrisez la table de 19. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  20: 'Maîtrisez la table de 20. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  21: 'Maîtrisez la table de 21. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  22: 'Maîtrisez la table de 22. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  23: 'Maîtrisez la table de 23. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  24: 'Maîtrisez la table de 24. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  25: 'Maîtrisez la table de 25. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  26: 'Maîtrisez la table de 26. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  27: 'Maîtrisez la table de 27. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  28: 'Maîtrisez la table de 28. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  29: 'Maîtrisez la table de 29. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  30: 'Maîtrisez la table de 30. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  31: 'Maîtrisez la table de 31. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  32: 'Maîtrisez la table de 32. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  33: 'Maîtrisez la table de 33. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  34: 'Maîtrisez la table de 34. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  35: 'Maîtrisez la table de 35. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  36: 'Maîtrisez la table de 36. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  37: 'Maîtrisez la table de 37. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  38: 'Maîtrisez la table de 38. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  39: 'Maîtrisez la table de 39. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  40: 'Maîtrisez la table de 40. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  41: 'Maîtrisez la table de 41. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  42: 'Maîtrisez la table de 42. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  43: 'Maîtrisez la table de 43. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  44: 'Maîtrisez la table de 44. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  45: 'Maîtrisez la table de 45. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  46: 'Maîtrisez la table de 46. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  47: 'Maîtrisez la table de 47. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  48: 'Maîtrisez la table de 48. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  49: 'Maîtrisez la table de 49. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  50: 'Maîtrisez la table de 50. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  51: 'Maîtrisez la table de 51. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  52: 'Maîtrisez la table de 52. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  53: 'Maîtrisez la table de 53. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  54: 'Maîtrisez la table de 54. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  55: 'Maîtrisez la table de 55. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  56: 'Maîtrisez la table de 56. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  57: 'Maîtrisez la table de 57. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  58: 'Maîtrisez la table de 58. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  59: 'Maîtrisez la table de 59. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  60: 'Maîtrisez la table de 60. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  61: 'Maîtrisez la table de 61. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  62: 'Maîtrisez la table de 62. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  63: 'Maîtrisez la table de 63. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  64: 'Maîtrisez la table de 64. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  65: 'Maîtrisez la table de 65. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  66: 'Maîtrisez la table de 66. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  67: 'Maîtrisez la table de 67. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  68: 'Maîtrisez la table de 68. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  69: 'Maîtrisez la table de 69. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  70: 'Maîtrisez la table de 70. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  71: 'Maîtrisez la table de 71. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  72: 'Maîtrisez la table de 72. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  73: 'Maîtrisez la table de 73. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  74: 'Maîtrisez la table de 74. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  75: 'Maîtrisez la table de 75. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  76: 'Maîtrisez la table de 76. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  77: 'Maîtrisez la table de 77. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  78: 'Maîtrisez la table de 78. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  79: 'Maîtrisez la table de 79. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  80: 'Maîtrisez la table de 80. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  81: 'Maîtrisez la table de 81. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  82: 'Maîtrisez la table de 82. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  83: 'Maîtrisez la table de 83. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  84: 'Maîtrisez la table de 84. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  85: 'Maîtrisez la table de 85. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  86: 'Maîtrisez la table de 86. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  87: 'Maîtrisez la table de 87. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  88: 'Maîtrisez la table de 88. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  89: 'Maîtrisez la table de 89. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  90: 'Maîtrisez la table de 90. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  91: 'Maîtrisez la table de 91. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  92: 'Maîtrisez la table de 92. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  93: 'Maîtrisez la table de 93. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  94: 'Maîtrisez la table de 94. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  95: 'Maîtrisez la table de 95. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  96: 'Maîtrisez la table de 96. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  97: 'Maîtrisez la table de 97. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  98: 'Maîtrisez la table de 98. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  99: 'Maîtrisez la table de 99. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
  100: 'Maîtrisez la table de 100. Explications claires, schémas et stratégies pratiques pour vous entraîner.',
}

export const numberSpecialPropertiesFr: Record<number, string> = {
  1: 'Tout nombre multiplié par 1 reste lui-même',
  2: 'Plus petit nombre premier, nombre pair',
  3: 'Plus petit nombre premier impair',
  4: 'Nombre pair, carré parfait (2×2)',
  5: 'Arrondi et décimales, 50% = moitié',
  6: 'Nombre pair, nombre parfait',
  7: 'Nombre impair, nombre premier',
  8: 'Nombre pair, cube parfait (2³)',
  9: 'Nombre impair, carré parfait (3×3)',
  10: 'Base du système décimal',
  11: 'Nombre impair, nombre premier, motif palindromique',
  12: 'Nombre pair, nombre hautement composé',
  13: 'Nombre impair, nombre premier',
  14: 'Nombre pair, 2×7',
  15: 'Nombre impair, 3×5',
  16: 'Nombre pair, carré parfait (4×4)',
  17: 'Nombre impair, nombre premier',
  18: 'Nombre pair, 2×9',
  19: 'Nombre impair, nombre premier',
  20: 'Nombre pair, 2×10',
  21: 'Nombre impair, 3×7',
  22: 'Nombre pair, 2×11',
  23: 'Nombre impair, nombre premier',
  24: 'Nombre pair, nombre hautement composé',
  25: 'Nombre impair, carré parfait (5×5)',
  26: 'Nombre pair, 2×13',
  27: 'Nombre impair, cube parfait (3³)',
  28: 'Nombre pair, nombre parfait',
  29: 'Nombre impair, nombre premier',
  30: 'Nombre pair, 3×10',
  31: 'Nombre impair, nombre premier',
  32: 'Nombre pair, 2⁵',
  33: 'Nombre impair, 3×11',
  34: 'Nombre pair, 2×17',
  35: 'Nombre impair, 5×7',
  36: 'Nombre pair, carré parfait (6×6)',
  37: 'Nombre impair, nombre premier',
  38: 'Nombre pair, 2×19',
  39: 'Nombre impair, 3×13',
  40: 'Nombre pair, 4×10',
  41: 'Nombre impair, nombre premier',
  42: 'Nombre pair, 6×7',
  43: 'Nombre impair, nombre premier',
  44: 'Nombre pair, 4×11',
  45: 'Nombre impair, 5×9',
  46: 'Nombre pair, 2×23',
  47: 'Nombre impair, nombre premier',
  48: 'Nombre pair, nombre hautement composé',
  49: 'Nombre impair, carré parfait (7×7)',
  50: 'Nombre pair, moitié de cent',
  51: 'Nombre impair, 3×17',
  52: 'Nombre pair, 4×13',
  53: 'Nombre impair, nombre premier',
  54: 'Nombre pair, 6×9',
  55: 'Nombre impair, 5×11',
  56: 'Nombre pair, 7×8',
  57: 'Nombre impair, 3×19',
  58: 'Nombre pair, 2×29',
  59: 'Nombre impair, nombre premier',
  60: 'Nombre pair, nombre hautement composé',
  61: 'Nombre impair, nombre premier',
  62: 'Nombre pair, 2×31',
  63: 'Nombre impair, 7×9',
  64: 'Nombre pair, carré parfait (8×8), cube parfait (4³)',
  65: 'Nombre impair, 5×13',
  66: 'Nombre pair, 6×11',
  67: 'Nombre impair, nombre premier',
  68: 'Nombre pair, 4×17',
  69: 'Nombre impair, 3×23',
  70: 'Nombre pair, 7×10',
  71: 'Nombre impair, nombre premier',
  72: 'Nombre pair, nombre hautement composé',
  73: 'Nombre impair, nombre premier',
  74: 'Nombre pair, 2×37',
  75: 'Nombre impair, 3×25',
  76: 'Nombre pair, 4×19',
  77: 'Nombre impair, 7×11',
  78: 'Nombre pair, 6×13',
  79: 'Nombre impair, nombre premier',
  80: 'Nombre pair, 8×10',
  81: 'Nombre impair, carré parfait (9×9)',
  82: 'Nombre pair, 2×41',
  83: 'Nombre impair, nombre premier',
  84: 'Nombre pair, 7×12',
  85: 'Nombre impair, 5×17',
  86: 'Nombre pair, 2×43',
  87: 'Nombre impair, 3×29',
  88: 'Nombre pair, 8×11',
  89: 'Nombre impair, nombre premier',
  90: 'Nombre pair, 9×10',
  91: 'Nombre impair, 7×13',
  92: 'Nombre pair, 4×23',
  93: 'Nombre impair, 3×31',
  94: 'Nombre pair, 2×47',
  95: 'Nombre impair, 5×19',
  96: 'Nombre pair, nombre hautement composé',
  97: 'Nombre impair, nombre premier',
  98: 'Nombre pair, 2×49',
  99: 'Nombre impair, 9×11',
  100: 'Nombre pair, carré parfait (10×10), jalon important',
}
