// Number-specific metadata for Spanish language
export const numberTitlesEs: Record<number, string> = {
  1: 'Tabla del 1',
  2: 'Tabla del 2',
  3: 'Tabla del 3',
  4: 'Tabla del 4',
  5: 'Tabla del 5',
  6: 'Tabla del 6',
  7: 'Tabla del 7',
  8: 'Tabla del 8',
  9: 'Tabla del 9',
  10: 'Tabla del 10',
  11: '11 Tabla de Multiplicar',
  12: '12 Tabla de Multiplicar',
  13: '13 Tabla de Multiplicar',
  14: '14 Tabla de Multiplicar',
  15: '15 Tabla de Multiplicar',
  16: '16 Tabla de Multiplicar',
  17: '17 Tabla de Multiplicar',
  18: '18 Tabla de Multiplicar',
  19: '19 Tabla de Multiplicar',
  20: '20 Tabla de Multiplicar',
  21: '21 Tabla de Multiplicar',
  22: '22 Tabla de Multiplicar',
  23: '23 Tabla de Multiplicar',
  24: '24 Tabla de Multiplicar',
  25: '25 Tabla de Multiplicar',
  26: '26 Tabla de Multiplicar',
  27: '27 Tabla de Multiplicar',
  28: '28 Tabla de Multiplicar',
  29: '29 Tabla de Multiplicar',
  30: '30 Tabla de Multiplicar',
  31: '31 Tabla de Multiplicar',
  32: '32 Tabla de Multiplicar',
  33: '33 Tabla de Multiplicar',
  34: '34 Tabla de Multiplicar',
  35: '35 Tabla de Multiplicar',
  36: '36 Tabla de Multiplicar',
  37: '37 Tabla de Multiplicar',
  38: '38 Tabla de Multiplicar',
  39: '39 Tabla de Multiplicar',
  40: '40 Tabla de Multiplicar',
  41: '41 Tabla de Multiplicar',
  42: '42 Tabla de Multiplicar',
  43: '43 Tabla de Multiplicar',
  44: '44 Tabla de Multiplicar',
  45: '45 Tabla de Multiplicar',
  46: '46 Tabla de Multiplicar',
  47: '47 Tabla de Multiplicar',
  48: '48 Tabla de Multiplicar',
  49: '49 Tabla de Multiplicar',
  50: '50 Tabla de Multiplicar',
  51: '51 Tabla de Multiplicar',
  52: '52 Tabla de Multiplicar',
  53: '53 Tabla de Multiplicar',
  54: '54 Tabla de Multiplicar',
  55: '55 Tabla de Multiplicar',
  56: '56 Tabla de Multiplicar',
  57: '57 Tabla de Multiplicar',
  58: '58 Tabla de Multiplicar',
  59: '59 Tabla de Multiplicar',
  60: '60 Tabla de Multiplicar',
  61: '61 Tabla de Multiplicar',
  62: '62 Tabla de Multiplicar',
  63: '63 Tabla de Multiplicar',
  64: '64 Tabla de Multiplicar',
  65: '65 Tabla de Multiplicar',
  66: '66 Tabla de Multiplicar',
  67: '67 Tabla de Multiplicar',
  68: '68 Tabla de Multiplicar',
  69: '69 Tabla de Multiplicar',
  70: '70 Tabla de Multiplicar',
  71: '71 Tabla de Multiplicar',
  72: '72 Tabla de Multiplicar',
  73: '73 Tabla de Multiplicar',
  74: '74 Tabla de Multiplicar',
  75: '75 Tabla de Multiplicar',
  76: '76 Tabla de Multiplicar',
  77: '77 Tabla de Multiplicar',
  78: '78 Tabla de Multiplicar',
  79: '79 Tabla de Multiplicar',
  80: '80 Tabla de Multiplicar',
  81: '81 Tabla de Multiplicar',
  82: '82 Tabla de Multiplicar',
  83: '83 Tabla de Multiplicar',
  84: '84 Tabla de Multiplicar',
  85: '85 Tabla de Multiplicar',
  86: '86 Tabla de Multiplicar',
  87: '87 Tabla de Multiplicar',
  88: '88 Tabla de Multiplicar',
  89: '89 Tabla de Multiplicar',
  90: '90 Tabla de Multiplicar',
  91: '91 Tabla de Multiplicar',
  92: '92 Tabla de Multiplicar',
  93: '93 Tabla de Multiplicar',
  94: '94 Tabla de Multiplicar',
  95: '95 Tabla de Multiplicar',
  96: '96 Tabla de Multiplicar',
  97: '97 Tabla de Multiplicar',
  98: '98 Tabla de Multiplicar',
  99: '99 Tabla de Multiplicar',
  100: '100 Tabla de Multiplicar',
}

export const numberDescriptionsEs: Record<number, string> = {
  1: 'Domina la tabla del 1. Explicaciones claras, patrones y estrategias prácticas para comprender la propiedad de identidad y sentar las bases de la multiplicación.',
  2: 'Domina la Tabla del 2. Explicaciones claras, patrones y estrategias prácticas para comprender la propiedad de identidad y sentar las bases de la multiplicación.',
  3: 'Domina la Tabla del 3. Explicaciones claras, patrones y estrategias prácticas para comprender la propiedad de identidad y sentar las bases de la multiplicación.',
  4: 'Domina la Tabla del 4. Explicaciones claras, patrones y estrategias prácticas para comprender la propiedad de identidad y sentar las bases de la multiplicación.',
  5: 'Domina la Tabla del 5. Explicaciones claras, patrones y estrategias prácticas para comprender la propiedad de identidad y sentar las bases de la multiplicación.',
  6: 'Aprende la tabla del 6 con juegos divertidos, ejercicios interactivos y hojas de trabajo imprimibles. Descubre herramientas de práctica gratuitas.',
  7: 'Aprende la tabla del 7 con juegos divertidos, ejercicios interactivos y hojas de trabajo imprimibles. Descubre herramientas de práctica gratuitas.',
  8: 'Aprende la tabla del 8 con juegos divertidos, ejercicios interactivos y hojas de trabajo imprimibles. Descubre herramientas de práctica gratuitas.',
  9: 'Aprende la tabla del 9 con juegos divertidos, ejercicios interactivos y hojas de trabajo imprimibles. Descubre herramientas de práctica gratuitas.',
  10: 'Aprende la tabla del 10 con juegos divertidos, ejercicios interactivos y hojas de trabajo imprimibles. Descubre herramientas de práctica gratuitas.',
  11: '11 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  12: '12 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  13: '13 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  14: '14 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  15: '15 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  16: '16 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  17: '17 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  18: '18 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  19: '19 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  20: '20 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  21: '21 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  22: '22 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  23: '23 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  24: '24 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  25: '25 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  26: '26 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  27: '27 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  28: '28 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  29: '29 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  30: '30 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  31: '31 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  32: '32 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  33: '33 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  34: '34 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  35: '35 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  36: '36 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  37: '37 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  38: '38 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  39: '39 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  40: '40 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  41: '41 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  42: '42 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  43: '43 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  44: '44 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  45: '45 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  46: '46 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  47: '47 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  48: '48 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  49: '49 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  50: '50 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos. Ayudas visuales para niños, consejos prácticos y técnicas fáciles de memorización.',
  51: '51 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  52: '52 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  53: '53 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  54: '54 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  55: '55 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  56: '56 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  57: '57 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  58: '58 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  59: '59 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  60: '60 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  61: '61 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  62: '62 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  63: '63 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  64: '64 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  65: '65 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  66: '66 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  67: '67 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  68: '68 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  69: '69 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  70: '70 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  71: '71 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  72: '72 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  73: '73 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  74: '74 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  75: '75 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  76: '76 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  77: '77 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  78: '78 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  79: '79 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  80: '80 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  81: '81 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  82: '82 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  83: '83 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  84: '84 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  85: '85 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  86: '86 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  87: '87 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  88: '88 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  89: '89 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  90: '90 Tabla de Multiplicar con juegos divertidos y ejercicios interactivos aprende. Perfecto para niños!',
  91: '91 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
  92: '92 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
  93: '93 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
  94: '94 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
  95: '95 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
  96: '96 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
  97: '97 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
  98: '98 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
  99: '99 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
  100: '100 Tabla de Multiplicar con métodos divertidos y efectivos. Domina la tabla con herramientas visuales y consejos prácticos.',
}

export const numberSpecialPropertiesEs: Record<number, string> = {
  1: 'Propiedad de Identidad',
  2: 'Duplicar',
  3: 'Agrupar de Tres',
  4: 'Duplicar Dos Veces',
  5: 'Contar de Cinco en Cinco',
  6: 'Patrones de Números Pares',
  7: 'Semana de Siete Días',
  8: 'Sistemas de Ocho',
  9: 'Truco de los Dedos',
  10: 'Sistema Decimal',
  11: 'Números de Dos Dígitos',
  12: 'Concepto de Docena',
  13: 'Número Primo',
  14: 'Cálculo de Semanas',
  15: 'Concepto de Cuarto de Hora',
  16: 'Números Cuadrados',
  17: 'Número Primo',
  18: 'Relación con 9 y 6',
  19: 'Estrategia 20-1',
  20: 'Sistema de Veinte',
  21: 'Relación 3×7',
  22: 'Relación 2×11',
  23: 'Número Primo',
  24: 'Sistema de 24 Horas',
  25: 'Concepto de Cuarto',
  26: 'Relación 2×13',
  27: 'Concepto de Cubo de 3',
  28: 'Concepto de Mes y Semana',
  29: 'Número Primo',
  30: 'Concepto de Media Hora',
  31: 'Días del Mes',
  32: 'Potencias de 2',
  33: 'Relación 3×11',
  34: 'Relación 2×17',
  35: 'Relación 5×7',
  36: 'Número Cuadrado',
  37: 'Número Primo',
  38: 'Múltiplos de 2',
  39: 'Múltiplos de 3',
  40: 'Múltiplos de 10',
  41: 'Número Primo',
  42: 'Múltiplos de 6',
  43: 'Número Primo',
  44: 'Múltiplos de 4',
  45: 'Múltiplos de 5',
  46: 'Múltiplos de 2',
  47: 'Número Primo',
  48: 'Múltiplos de 6',
  49: 'Número Cuadrado',
  50: 'Concepto de Mitad',
  51: 'Múltiplos de 3',
  52: 'Múltiplos de 4',
  53: 'Número Primo',
  54: 'Múltiplos de 6',
  55: 'Múltiplos de 5',
  56: 'Múltiplos de 7',
  57: 'Múltiplos de 3',
  58: 'Múltiplos de 2',
  59: 'Número Primo',
  60: 'Múltiplos de 10',
  61: 'Número Primo',
  62: 'Múltiplos de 2',
  63: 'Múltiplos de 7',
  64: 'Número Cuadrado',
  65: 'Múltiplos de 5',
  66: 'Múltiplos de 6',
  67: 'Número Primo',
  68: 'Múltiplos de 4',
  69: 'Múltiplos de 3',
  70: 'Múltiplos de 10',
  71: 'Número Primo',
  72: 'Múltiplos de 8',
  73: 'Número Primo',
  74: 'Múltiplos de 2',
  75: 'Múltiplos de 25',
  76: 'Múltiplos de 4',
  77: 'Múltiplos de 7',
  78: 'Múltiplos de 6',
  79: 'Número Primo',
  80: 'Múltiplos de 10',
  81: 'Número Cuadrado',
  82: 'Múltiplos de 2',
  83: 'Número Primo',
  84: 'Múltiplos de 12',
  85: 'Múltiplos de 5',
  86: 'Múltiplos de 2',
  87: 'Múltiplos de 3',
  88: 'Múltiplos de 8',
  89: 'Número Primo',
  90: 'Múltiplos de 10',
  91: 'Múltiplos de 7',
  92: 'Múltiplos de 4',
  93: 'Múltiplos de 3',
  94: 'Múltiplos de 2',
  95: 'Múltiplos de 5',
  96: 'Múltiplos de 12',
  97: 'Número Primo',
  98: 'Múltiplos de 7',
  99: 'Múltiplos de 9',
  100: 'Cuadrado de 10',
}
