// German metadata for number pages (1-100)

export const numberTitlesDe: Record<number, string> = {
  1: '1er-Einmaleins',
  2: '2er-Einmaleins',
  3: '3er-Einmaleins',
  4: '4er-Einmaleins',
  5: '5er-Einmaleins',
  6: '6er-Einmaleins',
  7: '7er-Einmaleins',
  8: '8er-Einmaleins',
  9: '9er-Einmaleins',
  10: '10er-Einmaleins',
  11: '11er-Einmaleins',
  12: '12er-Einmaleins',
  13: '13er-Einmaleins',
  14: '14er-Einmaleins',
  15: '15er-Einmaleins',
  16: '16er-Einmaleins',
  17: '17er-Einmaleins',
  18: '18er-Einmaleins',
  19: '19er-Einmaleins',
  20: '20er-Einmaleins',
  21: '21er-Einmaleins',
  22: '22er-Einmaleins',
  23: '23er-Einmaleins',
  24: '24er-Einmaleins',
  25: '25er-Einmaleins',
  26: '26er-Einmaleins',
  27: '27er-Einmaleins',
  28: '28er-Einmaleins',
  29: '29er-Einmaleins',
  30: '30er-Einmaleins',
  31: '31er-Einmaleins',
  32: '32er-Einmaleins',
  33: '33er-Einmaleins',
  34: '34er-Einmaleins',
  35: '35er-Einmaleins',
  36: '36er-Einmaleins',
  37: '37er-Einmaleins',
  38: '38er-Einmaleins',
  39: '39er-Einmaleins',
  40: '40er-Einmaleins',
  41: '41er-Einmaleins',
  42: '42er-Einmaleins',
  43: '43er-Einmaleins',
  44: '44er-Einmaleins',
  45: '45er-Einmaleins',
  46: '46er-Einmaleins',
  47: '47er-Einmaleins',
  48: '48er-Einmaleins',
  49: '49er-Einmaleins',
  50: '50er-Einmaleins',
  51: '51er-Einmaleins',
  52: '52er-Einmaleins',
  53: '53er-Einmaleins',
  54: '54er-Einmaleins',
  55: '55er-Einmaleins',
  56: '56er-Einmaleins',
  57: '57er-Einmaleins',
  58: '58er-Einmaleins',
  59: '59er-Einmaleins',
  60: '60er-Einmaleins',
  61: '61er-Einmaleins',
  62: '62er-Einmaleins',
  63: '63er-Einmaleins',
  64: '64er-Einmaleins',
  65: '65er-Einmaleins',
  66: '66er-Einmaleins',
  67: '67er-Einmaleins',
  68: '68er-Einmaleins',
  69: '69er-Einmaleins',
  70: '70er-Einmaleins',
  71: '71er-Einmaleins',
  72: '72er-Einmaleins',
  73: '73er-Einmaleins',
  74: '74er-Einmaleins',
  75: '75er-Einmaleins',
  76: '76er-Einmaleins',
  77: '77er-Einmaleins',
  78: '78er-Einmaleins',
  79: '79er-Einmaleins',
  80: '80er-Einmaleins',
  81: '81er-Einmaleins',
  82: '82er-Einmaleins',
  83: '83er-Einmaleins',
  84: '84er-Einmaleins',
  85: '85er-Einmaleins',
  86: '86er-Einmaleins',
  87: '87er-Einmaleins',
  88: '88er-Einmaleins',
  89: '89er-Einmaleins',
  90: '90er-Einmaleins',
  91: '91er-Einmaleins',
  92: '92er-Einmaleins',
  93: '93er-Einmaleins',
  94: '94er-Einmaleins',
  95: '95er-Einmaleins',
  96: '96er-Einmaleins',
  97: '97er-Einmaleins',
  98: '98er-Einmaleins',
  99: '99er-Einmaleins',
  100: '100er-Einmaleins',
}

export const numberDescriptionsDe: Record<number, string> = {
  1: 'Meistere das 1er-Einmaleins. Klare Erklärungen, Muster und praktische Strategien zum Verständnis der Identitätseigenschaft und der Grundlagen der Multiplikation.',
  2: 'Meistere das 2er-Einmaleins. Klare Erklärungen, Verdopplungsmuster und praktische Strategien zum Verständnis der Multiplikation mit 2.',
  3: 'Meistere das 3er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  4: 'Meistere das 4er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  5: 'Meistere das 5er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  6: 'Meistere das 6er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  7: 'Meistere das 7er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  8: 'Meistere das 8er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  9: 'Meistere das 9er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  10: 'Meistere das 10er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  11: 'Meistere das 11er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  12: 'Meistere das 12er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  13: 'Meistere das 13er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  14: 'Meistere das 14er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  15: 'Meistere das 15er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  16: 'Meistere das 16er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  17: 'Meistere das 17er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  18: 'Meistere das 18er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  19: 'Meistere das 19er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  20: 'Meistere das 20er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  21: 'Meistere das 21er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  22: 'Meistere das 22er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  23: 'Meistere das 23er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  24: 'Meistere das 24er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  25: 'Meistere das 25er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  26: 'Meistere das 26er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  27: 'Meistere das 27er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  28: 'Meistere das 28er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  29: 'Meistere das 29er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  30: 'Meistere das 30er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  31: 'Meistere das 31er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  32: 'Meistere das 32er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  33: 'Meistere das 33er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  34: 'Meistere das 34er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  35: 'Meistere das 35er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  36: 'Meistere das 36er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  37: 'Meistere das 37er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  38: 'Meistere das 38er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  39: 'Meistere das 39er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  40: 'Meistere das 40er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  41: 'Meistere das 41er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  42: 'Meistere das 42er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  43: 'Meistere das 43er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  44: 'Meistere das 44er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  45: 'Meistere das 45er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  46: 'Meistere das 46er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  47: 'Meistere das 47er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  48: 'Meistere das 48er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  49: 'Meistere das 49er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  50: 'Meistere das 50er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  51: 'Meistere das 51er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  52: 'Meistere das 52er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  53: 'Meistere das 53er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  54: 'Meistere das 54er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  55: 'Meistere das 55er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  56: 'Meistere das 56er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  57: 'Meistere das 57er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  58: 'Meistere das 58er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  59: 'Meistere das 59er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  60: 'Meistere das 60er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  61: 'Meistere das 61er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  62: 'Meistere das 62er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  63: 'Meistere das 63er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  64: 'Meistere das 64er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  65: 'Meistere das 65er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  66: 'Meistere das 66er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  67: 'Meistere das 67er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  68: 'Meistere das 68er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  69: 'Meistere das 69er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  70: 'Meistere das 70er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  71: 'Meistere das 71er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  72: 'Meistere das 72er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  73: 'Meistere das 73er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  74: 'Meistere das 74er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  75: 'Meistere das 75er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  76: 'Meistere das 76er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  77: 'Meistere das 77er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  78: 'Meistere das 78er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  79: 'Meistere das 79er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  80: 'Meistere das 80er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  81: 'Meistere das 81er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  82: 'Meistere das 82er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  83: 'Meistere das 83er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  84: 'Meistere das 84er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  85: 'Meistere das 85er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  86: 'Meistere das 86er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  87: 'Meistere das 87er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  88: 'Meistere das 88er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  89: 'Meistere das 89er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  90: 'Meistere das 90er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  91: 'Meistere das 91er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  92: 'Meistere das 92er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  93: 'Meistere das 93er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  94: 'Meistere das 94er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  95: 'Meistere das 95er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  96: 'Meistere das 96er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  97: 'Meistere das 97er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  98: 'Meistere das 98er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  99: 'Meistere das 99er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  100: 'Meistere das 100er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
}

export const numberSpecialPropertiesDe: Record<number, string> = {
  1: 'Identitätseigenschaft der Multiplikation',
  2: 'Gerade Zahl, Verdopplung',
  3: 'Ungerade Zahl, Dreiecksmuster',
  4: 'Gerade Zahl, Quadratzahl (2×2)',
  5: 'Ungerade Zahl, Halbierung von 10',
  6: 'Gerade Zahl, perfekte Zahl',
  7: 'Ungerade Zahl, Primzahl',
  8: 'Gerade Zahl, Kubikzahl (2³)',
  9: 'Ungerade Zahl, Quadratzahl (3×3)',
  10: 'Gerade Zahl, Basis des Dezimalsystems',
  11: 'Ungerade Zahl, Primzahl, Palindrom-Muster',
  12: 'Gerade Zahl, hochzusammengesetzte Zahl',
  13: 'Ungerade Zahl, Primzahl',
  14: 'Gerade Zahl, 2×7',
  15: 'Ungerade Zahl, 3×5',
  16: 'Gerade Zahl, Quadratzahl (4×4)',
  17: 'Ungerade Zahl, Primzahl',
  18: 'Gerade Zahl, 2×9',
  19: 'Ungerade Zahl, Primzahl',
  20: 'Gerade Zahl, 2×10',
  21: 'Ungerade Zahl, 3×7',
  22: 'Gerade Zahl, 2×11',
  23: 'Ungerade Zahl, Primzahl',
  24: 'Gerade Zahl, hochzusammengesetzte Zahl',
  25: 'Ungerade Zahl, Quadratzahl (5×5)',
  26: 'Gerade Zahl, 2×13',
  27: 'Ungerade Zahl, Kubikzahl (3³)',
  28: 'Gerade Zahl, perfekte Zahl',
  29: 'Ungerade Zahl, Primzahl',
  30: 'Gerade Zahl, 3×10',
  31: 'Ungerade Zahl, Primzahl',
  32: 'Gerade Zahl, 2⁵',
  33: 'Ungerade Zahl, 3×11',
  34: 'Gerade Zahl, 2×17',
  35: 'Ungerade Zahl, 5×7',
  36: 'Gerade Zahl, Quadratzahl (6×6)',
  37: 'Ungerade Zahl, Primzahl',
  38: 'Gerade Zahl, 2×19',
  39: 'Ungerade Zahl, 3×13',
  40: 'Gerade Zahl, 4×10',
  41: 'Ungerade Zahl, Primzahl',
  42: 'Gerade Zahl, 6×7',
  43: 'Ungerade Zahl, Primzahl',
  44: 'Gerade Zahl, 4×11',
  45: 'Ungerade Zahl, 5×9',
  46: 'Gerade Zahl, 2×23',
  47: 'Ungerade Zahl, Primzahl',
  48: 'Gerade Zahl, hochzusammengesetzte Zahl',
  49: 'Ungerade Zahl, Quadratzahl (7×7)',
  50: 'Gerade Zahl, halbes Hundert',
  51: 'Ungerade Zahl, 3×17',
  52: 'Gerade Zahl, 4×13',
  53: 'Ungerade Zahl, Primzahl',
  54: 'Gerade Zahl, 6×9',
  55: 'Ungerade Zahl, 5×11',
  56: 'Gerade Zahl, 7×8',
  57: 'Ungerade Zahl, 3×19',
  58: 'Gerade Zahl, 2×29',
  59: 'Ungerade Zahl, Primzahl',
  60: 'Gerade Zahl, hochzusammengesetzte Zahl',
  61: 'Ungerade Zahl, Primzahl',
  62: 'Gerade Zahl, 2×31',
  63: 'Ungerade Zahl, 7×9',
  64: 'Gerade Zahl, Quadratzahl (8×8), Kubikzahl (4³)',
  65: 'Ungerade Zahl, 5×13',
  66: 'Gerade Zahl, 6×11',
  67: 'Ungerade Zahl, Primzahl',
  68: 'Gerade Zahl, 4×17',
  69: 'Ungerade Zahl, 3×23',
  70: 'Gerade Zahl, 7×10',
  71: 'Ungerade Zahl, Primzahl',
  72: 'Gerade Zahl, hochzusammengesetzte Zahl',
  73: 'Ungerade Zahl, Primzahl',
  74: 'Gerade Zahl, 2×37',
  75: 'Ungerade Zahl, 3×25',
  76: 'Gerade Zahl, 4×19',
  77: 'Ungerade Zahl, 7×11',
  78: 'Gerade Zahl, 6×13',
  79: 'Ungerade Zahl, Primzahl',
  80: 'Gerade Zahl, 8×10',
  81: 'Ungerade Zahl, Quadratzahl (9×9)',
  82: 'Gerade Zahl, 2×41',
  83: 'Ungerade Zahl, Primzahl',
  84: 'Gerade Zahl, 7×12',
  85: 'Ungerade Zahl, 5×17',
  86: 'Gerade Zahl, 2×43',
  87: 'Ungerade Zahl, 3×29',
  88: 'Gerade Zahl, 8×11',
  89: 'Ungerade Zahl, Primzahl',
  90: 'Gerade Zahl, 9×10',
  91: 'Ungerade Zahl, 7×13',
  92: 'Gerade Zahl, 4×23',
  93: 'Ungerade Zahl, 3×31',
  94: 'Gerade Zahl, 2×47',
  95: 'Ungerade Zahl, 5×19',
  96: 'Gerade Zahl, hochzusammengesetzte Zahl',
  97: 'Ungerade Zahl, Primzahl',
  98: 'Gerade Zahl, 2×49',
  99: 'Ungerade Zahl, 9×11',
  100: 'Gerade Zahl, Quadratzahl (10×10), Meilenstein',
}
