// German metadata for number pages (1-100)

export const numberTitlesDe: Record<number, string> = {
  1: 'Das 1er-Einmaleins - Kostenlos Üben',
  2: 'Das 2er-Einmaleins - Kostenlos Üben',
  3: 'Das 3er-Einmaleins - Kostenlos Üben',
  4: 'Das 4er-Einmaleins - Kostenlos Üben',
  5: 'Das 5er-Einmaleins - Kostenlos Üben',
  6: 'Das 6er-Einmaleins - Kostenlos Üben',
  7: 'Das 7er-Einmaleins - Kostenlos Üben',
  8: 'Das 8er-Einmaleins - Kostenlos Üben',
  9: 'Das 9er-Einmaleins - Kostenlos Üben',
  10: 'Das 10er-Einmaleins - Kostenlos Üben',
  11: 'Das 11er-Einmaleins - Kostenlos Üben',
  12: 'Das 12er-Einmaleins - Kostenlos Üben',
  13: 'Das 13er-Einmaleins - Kostenlos Üben',
  14: 'Das 14er-Einmaleins - Kostenlos Üben',
  15: 'Das 15er-Einmaleins - Kostenlos Üben',
  16: 'Das 16er-Einmaleins - Kostenlos Üben',
  17: 'Das 17er-Einmaleins - Kostenlos Üben',
  18: 'Das 18er-Einmaleins - Kostenlos Üben',
  19: 'Das 19er-Einmaleins - Kostenlos Üben',
  20: 'Das 20er-Einmaleins - Kostenlos Üben',
  21: 'Das 21er-Einmaleins - Kostenlos Üben',
  22: 'Das 22er-Einmaleins - Kostenlos Üben',
  23: 'Das 23er-Einmaleins - Kostenlos Üben',
  24: 'Das 24er-Einmaleins - Kostenlos Üben',
  25: 'Das 25er-Einmaleins - Kostenlos Üben',
  26: 'Das 26er-Einmaleins - Kostenlos Üben',
  27: 'Das 27er-Einmaleins - Kostenlos Üben',
  28: 'Das 28er-Einmaleins - Kostenlos Üben',
  29: 'Das 29er-Einmaleins - Kostenlos Üben',
  30: 'Das 30er-Einmaleins - Kostenlos Üben',
  31: 'Das 31er-Einmaleins - Kostenlos Üben',
  32: 'Das 32er-Einmaleins - Kostenlos Üben',
  33: 'Das 33er-Einmaleins - Kostenlos Üben',
  34: 'Das 34er-Einmaleins - Kostenlos Üben',
  35: 'Das 35er-Einmaleins - Kostenlos Üben',
  36: 'Das 36er-Einmaleins - Kostenlos Üben',
  37: 'Das 37er-Einmaleins - Kostenlos Üben',
  38: 'Das 38er-Einmaleins - Kostenlos Üben',
  39: 'Das 39er-Einmaleins - Kostenlos Üben',
  40: 'Das 40er-Einmaleins - Kostenlos Üben',
  41: 'Das 41er-Einmaleins - Kostenlos Üben',
  42: 'Das 42er-Einmaleins - Kostenlos Üben',
  43: 'Das 43er-Einmaleins - Kostenlos Üben',
  44: 'Das 44er-Einmaleins - Kostenlos Üben',
  45: 'Das 45er-Einmaleins - Kostenlos Üben',
  46: 'Das 46er-Einmaleins - Kostenlos Üben',
  47: 'Das 47er-Einmaleins - Kostenlos Üben',
  48: 'Das 48er-Einmaleins - Kostenlos Üben',
  49: 'Das 49er-Einmaleins - Kostenlos Üben',
  50: 'Das 50er-Einmaleins - Kostenlos Üben',
  51: 'Das 51er-Einmaleins - Kostenlos Üben',
  52: 'Das 52er-Einmaleins - Kostenlos Üben',
  53: 'Das 53er-Einmaleins - Kostenlos Üben',
  54: 'Das 54er-Einmaleins - Kostenlos Üben',
  55: 'Das 55er-Einmaleins - Kostenlos Üben',
  56: 'Das 56er-Einmaleins - Kostenlos Üben',
  57: 'Das 57er-Einmaleins - Kostenlos Üben',
  58: 'Das 58er-Einmaleins - Kostenlos Üben',
  59: 'Das 59er-Einmaleins - Kostenlos Üben',
  60: 'Das 60er-Einmaleins - Kostenlos Üben',
  61: 'Das 61er-Einmaleins - Kostenlos Üben',
  62: 'Das 62er-Einmaleins - Kostenlos Üben',
  63: 'Das 63er-Einmaleins - Kostenlos Üben',
  64: 'Das 64er-Einmaleins - Kostenlos Üben',
  65: 'Das 65er-Einmaleins - Kostenlos Üben',
  66: 'Das 66er-Einmaleins - Kostenlos Üben',
  67: 'Das 67er-Einmaleins - Kostenlos Üben',
  68: 'Das 68er-Einmaleins - Kostenlos Üben',
  69: 'Das 69er-Einmaleins - Kostenlos Üben',
  70: 'Das 70er-Einmaleins - Kostenlos Üben',
  71: 'Das 71er-Einmaleins - Kostenlos Üben',
  72: 'Das 72er-Einmaleins - Kostenlos Üben',
  73: 'Das 73er-Einmaleins - Kostenlos Üben',
  74: 'Das 74er-Einmaleins - Kostenlos Üben',
  75: 'Das 75er-Einmaleins - Kostenlos Üben',
  76: 'Das 76er-Einmaleins - Kostenlos Üben',
  77: 'Das 77er-Einmaleins - Kostenlos Üben',
  78: 'Das 78er-Einmaleins - Kostenlos Üben',
  79: 'Das 79er-Einmaleins - Kostenlos Üben',
  80: 'Das 80er-Einmaleins - Kostenlos Üben',
  81: 'Das 81er-Einmaleins - Kostenlos Üben',
  82: 'Das 82er-Einmaleins - Kostenlos Üben',
  83: 'Das 83er-Einmaleins - Kostenlos Üben',
  84: 'Das 84er-Einmaleins - Kostenlos Üben',
  85: 'Das 85er-Einmaleins - Kostenlos Üben',
  86: 'Das 86er-Einmaleins - Kostenlos Üben',
  87: 'Das 87er-Einmaleins - Kostenlos Üben',
  88: 'Das 88er-Einmaleins - Kostenlos Üben',
  89: 'Das 89er-Einmaleins - Kostenlos Üben',
  90: 'Das 90er-Einmaleins - Kostenlos Üben',
  91: 'Das 91er-Einmaleins - Kostenlos Üben',
  92: 'Das 92er-Einmaleins - Kostenlos Üben',
  93: 'Das 93er-Einmaleins - Kostenlos Üben',
  94: 'Das 94er-Einmaleins - Kostenlos Üben',
  95: 'Das 95er-Einmaleins - Kostenlos Üben',
  96: 'Das 96er-Einmaleins - Kostenlos Üben',
  97: 'Das 97er-Einmaleins - Kostenlos Üben',
  98: 'Das 98er-Einmaleins - Kostenlos Üben',
  99: 'Das 99er-Einmaleins - Kostenlos Üben',
  100: 'Das 100er-Einmaleins - Kostenlos Üben',
}

export const numberDescriptionsDe: Record<number, string> = {
  1: 'Meistere das 1er-Einmaleins. Klare Erklärungen, Muster und praktische Strategien zum Verständnis der Identitätseigenschaft und der Grundlagen der Multiplikation.',
  2: 'Meistere das 2er-Einmaleins. Klare Erklärungen, Verdopplungsmuster und praktische Strategien zum Verständnis der Multiplikation mit 2.',
  3: 'Meistere das 3er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  4: 'Meistere das 4er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  5: 'Meistere das 5er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  6: 'Meistere das 6er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  7: 'Meistere das 7er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  8: 'Meistere das 8er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  9: 'Meistere das 9er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  10: 'Meistere das 10er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  11: 'Meistere das 11er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  12: 'Meistere das 12er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  13: 'Meistere das 13er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  14: 'Meistere das 14er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  15: 'Meistere das 15er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  16: 'Meistere das 16er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  17: 'Meistere das 17er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  18: 'Meistere das 18er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  19: 'Meistere das 19er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  20: 'Meistere das 20er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  21: 'Meistere das 21er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  22: 'Meistere das 22er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  23: 'Meistere das 23er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  24: 'Meistere das 24er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  25: 'Meistere das 25er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  26: 'Meistere das 26er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  27: 'Meistere das 27er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  28: 'Meistere das 28er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  29: 'Meistere das 29er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  30: 'Meistere das 30er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  31: 'Meistere das 31er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  32: 'Meistere das 32er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  33: 'Meistere das 33er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  34: 'Meistere das 34er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  35: 'Meistere das 35er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  36: 'Meistere das 36er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  37: 'Meistere das 37er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  38: 'Meistere das 38er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  39: 'Meistere das 39er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  40: 'Meistere das 40er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  41: 'Meistere das 41er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  42: 'Meistere das 42er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  43: 'Meistere das 43er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  44: 'Meistere das 44er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  45: 'Meistere das 45er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  46: 'Meistere das 46er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  47: 'Meistere das 47er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  48: 'Meistere das 48er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  49: 'Meistere das 49er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  50: 'Meistere das 50er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  51: 'Meistere das 51er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  52: 'Meistere das 52er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  53: 'Meistere das 53er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  54: 'Meistere das 54er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  55: 'Meistere das 55er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  56: 'Meistere das 56er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  57: 'Meistere das 57er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  58: 'Meistere das 58er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  59: 'Meistere das 59er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  60: 'Meistere das 60er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  61: 'Meistere das 61er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  62: 'Meistere das 62er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  63: 'Meistere das 63er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  64: 'Meistere das 64er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  65: 'Meistere das 65er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  66: 'Meistere das 66er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  67: 'Meistere das 67er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  68: 'Meistere das 68er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  69: 'Meistere das 69er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  70: 'Meistere das 70er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  71: 'Meistere das 71er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  72: 'Meistere das 72er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  73: 'Meistere das 73er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  74: 'Meistere das 74er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  75: 'Meistere das 75er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  76: 'Meistere das 76er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  77: 'Meistere das 77er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  78: 'Meistere das 78er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  79: 'Meistere das 79er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  80: 'Meistere das 80er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  81: 'Meistere das 81er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  82: 'Meistere das 82er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  83: 'Meistere das 83er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  84: 'Meistere das 84er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  85: 'Meistere das 85er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  86: 'Meistere das 86er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  87: 'Meistere das 87er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  88: 'Meistere das 88er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  89: 'Meistere das 89er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  90: 'Meistere das 90er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  91: 'Meistere das 91er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  92: 'Meistere das 92er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  93: 'Meistere das 93er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  94: 'Meistere das 94er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  95: 'Meistere das 95er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  96: 'Meistere das 96er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  97: 'Meistere das 97er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  98: 'Meistere das 98er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  99: 'Meistere das 99er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
  100: 'Meistere das 100er-Einmaleins. Klare Erklärungen, Muster und praktische Übungsstrategien.',
}

export const numberSpecialPropertiesDe: Record<number, string> = {
  1: 'Identitätseigenschaft der Multiplikation',
  2: 'Gerade Zahl, Verdopplung',
  3: 'Ungerade Zahl, Dreiecksmuster',
  4: 'Gerade Zahl, Quadratzahl (2×2)',
  5: 'Ungerade Zahl, Halbierung von 10',
  6: 'Gerade Zahl, perfekte Zahl',
  7: 'Ungerade Zahl, Primzahl',
  8: 'Gerade Zahl, Kubikzahl (2³)',
  9: 'Ungerade Zahl, Quadratzahl (3×3)',
  10: 'Gerade Zahl, Basis des Dezimalsystems',
  11: 'Ungerade Zahl, Primzahl, Palindrom-Muster',
  12: 'Gerade Zahl, hochzusammengesetzte Zahl',
  13: 'Ungerade Zahl, Primzahl',
  14: 'Gerade Zahl, 2×7',
  15: 'Ungerade Zahl, 3×5',
  16: 'Gerade Zahl, Quadratzahl (4×4)',
  17: 'Ungerade Zahl, Primzahl',
  18: 'Gerade Zahl, 2×9',
  19: 'Ungerade Zahl, Primzahl',
  20: 'Gerade Zahl, 2×10',
  21: 'Ungerade Zahl, 3×7',
  22: 'Gerade Zahl, 2×11',
  23: 'Ungerade Zahl, Primzahl',
  24: 'Gerade Zahl, hochzusammengesetzte Zahl',
  25: 'Ungerade Zahl, Quadratzahl (5×5)',
  26: 'Gerade Zahl, 2×13',
  27: 'Ungerade Zahl, Kubikzahl (3³)',
  28: 'Gerade Zahl, perfekte Zahl',
  29: 'Ungerade Zahl, Primzahl',
  30: 'Gerade Zahl, 3×10',
  31: 'Ungerade Zahl, Primzahl',
  32: 'Gerade Zahl, 2⁵',
  33: 'Ungerade Zahl, 3×11',
  34: 'Gerade Zahl, 2×17',
  35: 'Ungerade Zahl, 5×7',
  36: 'Gerade Zahl, Quadratzahl (6×6)',
  37: 'Ungerade Zahl, Primzahl',
  38: 'Gerade Zahl, 2×19',
  39: 'Ungerade Zahl, 3×13',
  40: 'Gerade Zahl, 4×10',
  41: 'Ungerade Zahl, Primzahl',
  42: 'Gerade Zahl, 6×7',
  43: 'Ungerade Zahl, Primzahl',
  44: 'Gerade Zahl, 4×11',
  45: 'Ungerade Zahl, 5×9',
  46: 'Gerade Zahl, 2×23',
  47: 'Ungerade Zahl, Primzahl',
  48: 'Gerade Zahl, hochzusammengesetzte Zahl',
  49: 'Ungerade Zahl, Quadratzahl (7×7)',
  50: 'Gerade Zahl, halbes Hundert',
  51: 'Ungerade Zahl, 3×17',
  52: 'Gerade Zahl, 4×13',
  53: 'Ungerade Zahl, Primzahl',
  54: 'Gerade Zahl, 6×9',
  55: 'Ungerade Zahl, 5×11',
  56: 'Gerade Zahl, 7×8',
  57: 'Ungerade Zahl, 3×19',
  58: 'Gerade Zahl, 2×29',
  59: 'Ungerade Zahl, Primzahl',
  60: 'Gerade Zahl, hochzusammengesetzte Zahl',
  61: 'Ungerade Zahl, Primzahl',
  62: 'Gerade Zahl, 2×31',
  63: 'Ungerade Zahl, 7×9',
  64: 'Gerade Zahl, Quadratzahl (8×8), Kubikzahl (4³)',
  65: 'Ungerade Zahl, 5×13',
  66: 'Gerade Zahl, 6×11',
  67: 'Ungerade Zahl, Primzahl',
  68: 'Gerade Zahl, 4×17',
  69: 'Ungerade Zahl, 3×23',
  70: 'Gerade Zahl, 7×10',
  71: 'Ungerade Zahl, Primzahl',
  72: 'Gerade Zahl, hochzusammengesetzte Zahl',
  73: 'Ungerade Zahl, Primzahl',
  74: 'Gerade Zahl, 2×37',
  75: 'Ungerade Zahl, 3×25',
  76: 'Gerade Zahl, 4×19',
  77: 'Ungerade Zahl, 7×11',
  78: 'Gerade Zahl, 6×13',
  79: 'Ungerade Zahl, Primzahl',
  80: 'Gerade Zahl, 8×10',
  81: 'Ungerade Zahl, Quadratzahl (9×9)',
  82: 'Gerade Zahl, 2×41',
  83: 'Ungerade Zahl, Primzahl',
  84: 'Gerade Zahl, 7×12',
  85: 'Ungerade Zahl, 5×17',
  86: 'Gerade Zahl, 2×43',
  87: 'Ungerade Zahl, 3×29',
  88: 'Gerade Zahl, 8×11',
  89: 'Ungerade Zahl, Primzahl',
  90: 'Gerade Zahl, 9×10',
  91: 'Ungerade Zahl, 7×13',
  92: 'Gerade Zahl, 4×23',
  93: 'Ungerade Zahl, 3×31',
  94: 'Gerade Zahl, 2×47',
  95: 'Ungerade Zahl, 5×19',
  96: 'Gerade Zahl, hochzusammengesetzte Zahl',
  97: 'Ungerade Zahl, Primzahl',
  98: 'Gerade Zahl, 2×49',
  99: 'Ungerade Zahl, 9×11',
  100: 'Gerade Zahl, Quadratzahl (10×10), Meilenstein',
}
