export const numberTitlesId: Record<number, string> = {
  1: "Tabel Perkalian 1 | Belajar mengalikan dengan 1",
  2: "Tabel Perkalian 2 | Belajar mengalikan dengan 2",
  3: "Tabel Perkalian 3 | Belajar mengalikan dengan 3",
  4: "Tabel Perkalian 4 | Belajar mengalikan dengan 4",
  5: "Tabel Perkalian 5 | Belajar mengalikan dengan 5",
  6: "Tabel Perkalian 6 | Belajar mengalikan dengan 6",
  7: "Tabel Perkalian 7 | Belajar mengalikan dengan 7",
  8: "Tabel Perkalian 8 | Belajar mengalikan dengan 8",
  9: "Tabel Perkalian 9 | Belajar mengalikan dengan 9",
  10: "Tabel Perkalian 10 | Belajar mengalikan dengan 10",
  11: "Tabel Perkalian 11 | Belajar mengalikan dengan 11",
  12: "Tabel Perkalian 12 | Belajar mengalikan dengan 12",
  13: "Tabel Perkalian 13 | Belajar mengalikan dengan 13",
  14: "Tabel Perkalian 14 | Belajar mengalikan dengan 14",
  15: "Tabel Perkalian 15 | Belajar mengalikan dengan 15",
  16: "Tabel Perkalian 16 | Belajar mengalikan dengan 16",
  17: "Tabel Perkalian 17 | Belajar mengalikan dengan 17",
  18: "Tabel Perkalian 18 | Belajar mengalikan dengan 18",
  19: "Tabel Perkalian 19 | Belajar mengalikan dengan 19",
  20: "Tabel Perkalian 20 | Belajar mengalikan dengan 20",
  21: "Tabel Perkalian 21 | Belajar mengalikan dengan 21",
  22: "Tabel Perkalian 22 | Belajar mengalikan dengan 22",
  23: "Tabel Perkalian 23 | Belajar mengalikan dengan 23",
  24: "Tabel Perkalian 24 | Belajar mengalikan dengan 24",
  25: "Tabel Perkalian 25 | Belajar mengalikan dengan 25",
  26: "Tabel Perkalian 26 | Belajar mengalikan dengan 26",
  27: "Tabel Perkalian 27 | Belajar mengalikan dengan 27",
  28: "Tabel Perkalian 28 | Belajar mengalikan dengan 28",
  29: "Tabel Perkalian 29 | Belajar mengalikan dengan 29",
  30: "Tabel Perkalian 30 | Belajar mengalikan dengan 30",
  31: "Tabel Perkalian 31 | Belajar mengalikan dengan 31",
  32: "Tabel Perkalian 32 | Belajar mengalikan dengan 32",
  33: "Tabel Perkalian 33 | Belajar mengalikan dengan 33",
  34: "Tabel Perkalian 34 | Belajar mengalikan dengan 34",
  35: "Tabel Perkalian 35 | Belajar mengalikan dengan 35",
  36: "Tabel Perkalian 36 | Belajar mengalikan dengan 36",
  37: "Tabel Perkalian 37 | Belajar mengalikan dengan 37",
  38: "Tabel Perkalian 38 | Belajar mengalikan dengan 38",
  39: "Tabel Perkalian 39 | Belajar mengalikan dengan 39",
  40: "Tabel Perkalian 40 | Belajar mengalikan dengan 40",
  41: "Tabel Perkalian 41 | Belajar mengalikan dengan 41",
  42: "Tabel Perkalian 42 | Belajar mengalikan dengan 42",
  43: "Tabel Perkalian 43 | Belajar mengalikan dengan 43",
  44: "Tabel Perkalian 44 | Belajar mengalikan dengan 44",
  45: "Tabel Perkalian 45 | Belajar mengalikan dengan 45",
  46: "Tabel Perkalian 46 | Belajar mengalikan dengan 46",
  47: "Tabel Perkalian 47 | Belajar mengalikan dengan 47",
  48: "Tabel Perkalian 48 | Belajar mengalikan dengan 48",
  49: "Tabel Perkalian 49 | Belajar mengalikan dengan 49",
  50: "Tabel Perkalian 50 | Belajar mengalikan dengan 50",
  51: "Tabel Perkalian 51 | Belajar mengalikan dengan 51",
  52: "Tabel Perkalian 52 | Belajar mengalikan dengan 52",
  53: "Tabel Perkalian 53 | Belajar mengalikan dengan 53",
  54: "Tabel Perkalian 54 | Belajar mengalikan dengan 54",
  55: "Tabel Perkalian 55 | Belajar mengalikan dengan 55",
  56: "Tabel Perkalian 56 | Belajar mengalikan dengan 56",
  57: "Tabel Perkalian 57 | Belajar mengalikan dengan 57",
  58: "Tabel Perkalian 58 | Belajar mengalikan dengan 58",
  59: "Tabel Perkalian 59 | Belajar mengalikan dengan 59",
  60: "Tabel Perkalian 60 | Belajar mengalikan dengan 60",
  61: "Tabel Perkalian 61 | Belajar mengalikan dengan 61",
  62: "Tabel Perkalian 62 | Belajar mengalikan dengan 62",
  63: "Tabel Perkalian 63 | Belajar mengalikan dengan 63",
  64: "Tabel Perkalian 64 | Belajar mengalikan dengan 64",
  65: "Tabel Perkalian 65 | Belajar mengalikan dengan 65",
  66: "Tabel Perkalian 66 | Belajar mengalikan dengan 66",
  67: "Tabel Perkalian 67 | Belajar mengalikan dengan 67",
  68: "Tabel Perkalian 68 | Belajar mengalikan dengan 68",
  69: "Tabel Perkalian 69 | Belajar mengalikan dengan 69",
  70: "Tabel Perkalian 70 | Belajar mengalikan dengan 70",
  71: "Tabel Perkalian 71 | Belajar mengalikan dengan 71",
  72: "Tabel Perkalian 72 | Belajar mengalikan dengan 72",
  73: "Tabel Perkalian 73 | Belajar mengalikan dengan 73",
  74: "Tabel Perkalian 74 | Belajar mengalikan dengan 74",
  75: "Tabel Perkalian 75 | Belajar mengalikan dengan 75",
  76: "Tabel Perkalian 76 | Belajar mengalikan dengan 76",
  77: "Tabel Perkalian 77 | Belajar mengalikan dengan 77",
  78: "Tabel Perkalian 78 | Belajar mengalikan dengan 78",
  79: "Tabel Perkalian 79 | Belajar mengalikan dengan 79",
  80: "Tabel Perkalian 80 | Belajar mengalikan dengan 80",
  81: "Tabel Perkalian 81 | Belajar mengalikan dengan 81",
  82: "Tabel Perkalian 82 | Belajar mengalikan dengan 82",
  83: "Tabel Perkalian 83 | Belajar mengalikan dengan 83",
  84: "Tabel Perkalian 84 | Belajar mengalikan dengan 84",
  85: "Tabel Perkalian 85 | Belajar mengalikan dengan 85",
  86: "Tabel Perkalian 86 | Belajar mengalikan dengan 86",
  87: "Tabel Perkalian 87 | Belajar mengalikan dengan 87",
  88: "Tabel Perkalian 88 | Belajar mengalikan dengan 88",
  89: "Tabel Perkalian 89 | Belajar mengalikan dengan 89",
  90: "Tabel Perkalian 90 | Belajar mengalikan dengan 90",
  91: "Tabel Perkalian 91 | Belajar mengalikan dengan 91",
  92: "Tabel Perkalian 92 | Belajar mengalikan dengan 92",
  93: "Tabel Perkalian 93 | Belajar mengalikan dengan 93",
  94: "Tabel Perkalian 94 | Belajar mengalikan dengan 94",
  95: "Tabel Perkalian 95 | Belajar mengalikan dengan 95",
  96: "Tabel Perkalian 96 | Belajar mengalikan dengan 96",
  97: "Tabel Perkalian 97 | Belajar mengalikan dengan 97",
  98: "Tabel Perkalian 98 | Belajar mengalikan dengan 98",
  99: "Tabel Perkalian 99 | Belajar mengalikan dengan 99",
  100: "Tabel Perkalian 100 | Belajar mengalikan dengan 100",
}

export const numberDescriptionsId: Record<number, string> = {
  1: "Pelajari tabel perkalian 1 dengan penjelasan mudah dipahami, contoh visual, dan latihan interaktif. Dasar dari semua tabel perkalian - setiap angka dikalikan 1 tetap sama.",
  2: "Kuasai tabel perkalian 2 dengan latihan yang menyenangkan. Belajar menggandakan angka dengan mudah - fondasi penting untuk matematika mental yang cepat.",
  3: "Temukan pola dalam tabel perkalian 3. Pelajari cara menghitung dengan 3 dan kenali trik yang membuat perkalian 3 mudah diingat.",
  4: "Tabel perkalian 4 menjadi mudah dengan panduan langkah demi langkah kami. Pelajari cara menggandakan dua kali untuk hasil yang cepat.",
  5: "Master tabel perkalian 5 - salah satu yang termudah! Semua jawaban berakhir dengan 0 atau 5. Latihan interaktif dan permainan tersedia.",
  6: "Pelajari tabel perkalian 6 dengan contoh praktis dan visualisasi yang jelas. Kombinasikan pengetahuan dari tabel 2 dan 3.",
  7: "Tabel perkalian 7 dijelaskan dengan cara yang mudah. Tips memori, pola, dan latihan praktek untuk menguasai perkalian 7.",
  8: "Kuasai tabel perkalian 8 melalui teknik penggandaan. Pelajari pola dan trik untuk mengingat perkalian 8 dengan mudah.",
  9: "Temukan keajaiban tabel perkalian 9! Pola jari terkenal dan trik digit yang membuat pembelajaran menjadi menyenangkan.",
  10: "Tabel perkalian 10 adalah yang termudah - cukup tambahkan nol! Latihan dan aplikasi di dunia nyata.",
  11: "Belajar tabel perkalian 11 - angka berulang membuatnya mudah diingat dan menyenangkan untuk dipelajari.",
  12: "Tabel perkalian 12: Penting untuk membaca waktu dan pengukuran. Panduan lengkap dengan tips dan latihan.",
  13: "Tabel perkalian 13: Angka baru mulai dari sini. Pelajari dengan contoh visual, latihan interaktif, dan permainan edukatif.",
  14: "Tabel perkalian 14: Gunakan pengetahuan dari tabel 2 dan 7. Latihan praktek dan tips untuk menghafal.",
  15: "Tabel perkalian 15: Gabungan dari 10 dan 5. Pelajari dengan metode yang terstruktur dan latihan interaktif.",
  16: "Tabel perkalian 16: Menggandakan empat kali. Penjelasan lengkap dengan strategi pembelajaran yang efektif.",
  17: "Tabel perkalian 17: Tingkatkan keterampilan matematika Anda. Latihan dan permainan untuk pembelajaran yang menyenangkan.",
  18: "Tabel perkalian 18: Latihan interaktif dan lembar kerja PDF. Pelajari dengan tempo Anda sendiri.",
  19: "Tabel perkalian 19: Strategi pembelajaran yang efektif. Latihan harian dan permainan edukatif.",
  20: "Tabel perkalian 20: Mudah dengan akhiran nol. Pelajari dengan cepat melalui latihan interaktif.",
  21: "Tabel perkalian 21: Tingkatkan ke level berikutnya. Latihan komprehensif dan permainan untuk master perkalian.",
  22: "Tabel perkalian 22: Pelajari dengan metode yang terbukti efektif. Latihan interaktif dan lembar kerja tersedia.",
  23: "Tabel perkalian 23: Kembangkan keterampilan matematika lanjutan. Latihan yang menantang dan permainan edukatif.",
  24: "Tabel perkalian 24: Kombinasi dari 12×2. Pelajari dengan strategi yang terstruktur dan latihan praktek.",
  25: "Tabel perkalian 25: Pola 25, 50, 75, 00. Mudah diingat dengan tips dan trik khusus.",
  26: "Tabel perkalian 26: Tingkatkan kemampuan perhitungan mental Anda. Latihan komprehensif tersedia.",
  27: "Tabel perkalian 27: Kelipatan dari 3×9. Pelajari dengan penjelasan yang jelas dan latihan interaktif.",
  28: "Tabel perkalian 28: Kombinasi dari 4×7. Strategi pembelajaran yang efektif dan latihan praktek.",
  29: "Tabel perkalian 29: Tingkatkan keterampilan matematika Anda. Latihan dan permainan untuk pembelajaran optimal.",
  30: "Tabel perkalian 30: Mudah dengan akhiran 0. Pelajari dengan cepat melalui latihan interaktif dan permainan.",
  31: "Tabel perkalian 31: Kembangkan kemampuan perkalian lanjutan. Latihan komprehensif dan lembar kerja PDF.",
  32: "Tabel perkalian 32: Penggandaan lima kali. Pelajari dengan metode yang terstruktur dan latihan praktek.",
  33: "Tabel perkalian 33: Pola angka berulang. Tips memori dan latihan interaktif tersedia.",
  34: "Tabel perkalian 34: Kombinasi dari 17×2. Strategi pembelajaran yang efektif dengan latihan.",
  35: "Tabel perkalian 35: Gabungan dari 5×7. Mudah diingat dengan pola khusus dan latihan.",
  36: "Tabel perkalian 36: Square dari 6. Pelajari dengan penjelasan lengkap dan latihan interaktif.",
  37: "Tabel perkalian 37: Tingkatkan keterampilan matematika Anda. Latihan komprehensif dan permainan edukatif.",
  38: "Tabel perkalian 38: Kombinasi dari 19×2. Strategi pembelajaran yang jelas dengan latihan praktek.",
  39: "Tabel perkalian 39: Kelipatan dari 13×3. Pelajari dengan metode yang efektif dan latihan interaktif.",
  40: "Tabel perkalian 40: Mudah dengan akhiran 0. Latihan cepat dan permainan untuk master perkalian.",
  41: "Tabel perkalian 41: Kembangkan kemampuan perhitungan mental lanjutan. Latihan dan lembar kerja tersedia.",
  42: "Tabel perkalian 42: Kombinasi dari 6×7. Pelajari dengan strategi yang terbukti efektif.",
  43: "Tabel perkalian 43: Tingkatkan keterampilan matematika Anda. Latihan komprehensif dan permainan interaktif.",
  44: "Tabel perkalian 44: Kelipatan dari 11×4. Mudah diingat dengan pola dan tips khusus.",
  45: "Tabel perkalian 45: Gabungan dari 5×9. Pelajari dengan metode yang terstruktur dan latihan praktek.",
  46: "Tabel perkalian 46: Kombinasi dari 23×2. Strategi pembelajaran yang efektif dengan latihan interaktif.",
  47: "Tabel perkalian 47: Kembangkan kemampuan perkalian lanjutan. Latihan dan permainan edukatif tersedia.",
  48: "Tabel perkalian 48: Kelipatan dari 6×8. Pelajari dengan penjelasan lengkap dan latihan komprehensif.",
  49: "Tabel perkalian 49: Square dari 7. Tips memori dan latihan interaktif untuk master perkalian.",
  50: "Tabel perkalian 50: Mudah dengan akhiran 0 atau 50. Latihan cepat dan permainan untuk pembelajaran optimal.",
  51: "Tabel perkalian 51: Tingkatkan keterampilan matematika Anda. Latihan komprehensif dan lembar kerja PDF.",
  52: "Tabel perkalian 52: Kombinasi dari 13×4. Pelajari dengan strategi yang terstruktur dan latihan praktek.",
  53: "Tabel perkalian 53: Kembangkan kemampuan perhitungan mental lanjutan. Latihan dan permainan interaktif.",
  54: "Tabel perkalian 54: Kelipatan dari 6×9. Mudah diingat dengan pola dan tips khusus.",
  55: "Tabel perkalian 55: Pola 55, 10, 65, 20. Pelajari dengan metode yang efektif dan latihan interaktif.",
  56: "Tabel perkalian 56: Kombinasi dari 7×8. Strategi pembelajaran yang jelas dengan latihan komprehensif.",
  57: "Tabel perkalian 57: Kelipatan dari 19×3. Tingkatkan keterampilan matematika Anda dengan latihan.",
  58: "Tabel perkalian 58: Kombinasi dari 29×2. Pelajari dengan penjelasan lengkap dan latihan interaktif.",
  59: "Tabel perkalian 59: Kembangkan kemampuan perkalian lanjutan. Latihan dan permainan edukatif tersedia.",
  60: "Tabel perkalian 60: Mudah dengan akhiran 0. Latihan cepat dan permainan untuk master perkalian.",
  61: "Tabel perkalian 61: Tingkatkan keterampilan matematika Anda. Latihan komprehensif dan lembar kerja tersedia.",
  62: "Tabel perkalian 62: Kombinasi dari 31×2. Pelajari dengan strategi yang terstruktur dan latihan praktek.",
  63: "Tabel perkalian 63: Kelipatan dari 7×9. Mudah diingat dengan pola dan tips khusus.",
  64: "Tabel perkalian 64: Square dari 8. Pelajari dengan metode yang efektif dan latihan interaktif.",
  65: "Tabel perkalian 65: Gabungan dari 5×13. Strategi pembelajaran yang jelas dengan latihan komprehensif.",
  66: "Tabel perkalian 66: Kombinasi dari 6×11. Tingkatkan keterampilan matematika Anda dengan latihan.",
  67: "Tabel perkalian 67: Kembangkan kemampuan perhitungan mental lanjutan. Latihan dan permainan interaktif.",
  68: "Tabel perkalian 68: Kombinasi dari 17×4. Pelajari dengan penjelasan lengkap dan latihan praktek.",
  69: "Tabel perkalian 69: Kelipatan dari 23×3. Mudah diingat dengan pola dan tips khusus.",
  70: "Tabel perkalian 70: Mudah dengan akhiran 0. Latihan cepat dan permainan untuk pembelajaran optimal.",
  71: "Tabel perkalian 71: Tingkatkan keterampilan matematika Anda. Latihan komprehensif dan lembar kerja PDF.",
  72: "Tabel perkalian 72: Kombinasi dari 8×9. Pelajari dengan strategi yang terstruktur dan latihan interaktif.",
  73: "Tabel perkalian 73: Kembangkan kemampuan perkalian lanjutan. Latihan dan permainan edukatif tersedia.",
  74: "Tabel perkalian 74: Kombinasi dari 37×2. Mudah diingat dengan pola dan tips khusus.",
  75: "Tabel perkalian 75: Gabungan dari 25×3. Pelajari dengan metode yang efektif dan latihan praktek.",
  76: "Tabel perkalian 76: Kombinasi dari 19×4. Strategi pembelajaran yang jelas dengan latihan komprehensif.",
  77: "Tabel perkalian 77: Kelipatan dari 7×11. Tingkatkan keterampilan matematika Anda dengan latihan.",
  78: "Tabel perkalian 78: Kombinasi dari 13×6. Pelajari dengan penjelasan lengkap dan latihan interaktif.",
  79: "Tabel perkalian 79: Kembangkan kemampuan perhitungan mental lanjutan. Latihan dan permainan tersedia.",
  80: "Tabel perkalian 80: Mudah dengan akhiran 0. Latihan cepat dan permainan untuk master perkalian.",
  81: "Tabel perkalian 81: Square dari 9. Tingkatkan keterampilan matematika Anda dengan latihan komprehensif.",
  82: "Tabel perkalian 82: Kombinasi dari 41×2. Pelajari dengan strategi yang terstruktur dan latihan praktek.",
  83: "Tabel perkalian 83: Kembangkan kemampuan perkalian lanjutan. Latihan dan permainan edukatif tersedia.",
  84: "Tabel perkalian 84: Kombinasi dari 12×7. Mudah diingat dengan pola dan tips khusus.",
  85: "Tabel Perkalian 85: Gabungan dari 5×17. Pelajari dengan metode yang efektif dan latihan interaktif.",
  86: "Tabel perkalian 86: Kombinasi dari 43×2. Strategi pembelajaran yang jelas dengan latihan komprehensif.",
  87: "Tabel perkalian 87: Kelipatan dari 29×3. Tingkatkan keterampilan matematika Anda dengan latihan.",
  88: "Tabel perkalian 88: Kombinasi dari 11×8. Pelajari dengan penjelasan lengkap dan latihan praktek.",
  89: "Tabel perkalian 89: Kembangkan kemampuan perhitungan mental lanjutan. Latihan dan permainan interaktif.",
  90: "Tabel perkalian 90: Mudah dengan akhiran 0. Latihan cepat dan permainan untuk pembelajaran optimal.",
  91: "Tabel perkalian 91: Kombinasi dari 7×13. Tingkatkan keterampilan matematika Anda dengan latihan.",
  92: "Tabel perkalian 92: Kombinasi dari 23×4. Pelajari dengan strategi yang terstruktur dan latihan praktek.",
  93: "Tabel perkalian 93: Kelipatan dari 31×3. Kembangkan kemampuan perkalian lanjutan dengan latihan.",
  94: "Tabel perkalian 94: Kombinasi dari 47×2. Mudah diingat dengan pola dan tips khusus.",
  95: "Tabel perkalian 95: Gabungan dari 5×19. Pelajari dengan metode yang efektif dan latihan interaktif.",
  96: "Tabel perkalian 96: Kombinasi dari 12×8. Strategi pembelajaran yang jelas dengan latihan komprehensif.",
  97: "Tabel perkalian 97: Tingkatkan keterampilan matematika Anda. Latihan dan permainan edukatif tersedia.",
  98: "Tabel perkalian 98: Kombinasi dari 49×2. Pelajari dengan penjelasan lengkap dan latihan praktek.",
  99: "Tabel perkalian 99: Kelipatan dari 11×9. Kembangkan kemampuan perhitungan mental lanjutan dengan latihan.",
  100: "Tabel perkalian 100: Mudah dengan akhiran 00. Latihan cepat dan permainan untuk master perkalian.",
}

export const numberSpecialPropertiesId: Record<number, string> = {
  1: "Sifat Identitas",
  2: "Penggandaan",
  3: "Pola Jumlah Digit",
  4: "Gandakan Dua Kali",
  5: "Berakhir dengan 0 atau 5",
  6: "Gabungan 2 dan 3",
  7: "Pola Berulang",
  8: "Penggandaan Tiga Kali",
  9: "Trik Jari & Pola Digit",
  10: "Tambahkan Nol",
}

export const numberKeywordsId: Record<number, string[]> = {
  1: ["tabel perkalian 1", "belajar perkalian 1", "sifat identitas", "dasar perkalian"],
  2: ["tabel perkalian 2", "menggandakan angka", "perkalian genap", "belajar perkalian 2"],
  3: ["tabel perkalian 3", "perkalian 3", "pola tabel 3", "belajar perkalian 3"],
  4: ["tabel perkalian 4", "perkalian 4", "gandakan dua kali", "belajar perkalian 4"],
  5: ["tabel perkalian 5", "perkalian 5", "pola 0 dan 5", "belajar perkalian 5"],
  6: ["tabel perkalian 6", "perkalian 6", "belajar perkalian 6", "trik perkalian 6"],
  7: ["tabel perkalian 7", "perkalian 7", "belajar perkalian 7", "trik perkalian 7"],
  8: ["tabel perkalian 8", "perkalian 8", "belajar perkalian 8", "trik perkalian 8"],
  9: ["tabel perkalian 9", "perkalian 9", "trik jari perkalian 9", "belajar perkalian 9"],
  10: ["tabel perkalian 10", "perkalian 10", "tambahkan nol", "belajar perkalian 10"],
  11: ["tabel perkalian 11", "perkalian 11", "angka berulang", "belajar perkalian 11"],
  12: ["tabel perkalian 12", "perkalian 12", "lusin", "belajar perkalian 12"],
  13: ["tabel perkalian 13", "perkalian 13", "belajar perkalian 13"],
  14: ["tabel perkalian 14", "perkalian 14", "belajar perkalian 14"],
  15: ["tabel perkalian 15", "perkalian 15", "belajar perkalian 15"],
  16: ["tabel perkalian 16", "perkalian 16", "belajar perkalian 16"],
  17: ["tabel perkalian 17", "perkalian 17", "belajar perkalian 17"],
  18: ["tabel perkalian 18", "perkalian 18", "belajar perkalian 18"],
  19: ["tabel perkalian 19", "perkalian 19", "belajar perkalian 19"],
  20: ["tabel perkalian 20", "perkalian 20", "belajar perkalian 20"],
  21: ["tabel perkalian 21", "perkalian 21", "belajar perkalian 21"],
  22: ["tabel perkalian 22", "perkalian 22", "belajar perkalian 22"],
  23: ["tabel perkalian 23", "perkalian 23", "belajar perkalian 23"],
  24: ["tabel perkalian 24", "perkalian 24", "belajar perkalian 24"],
  25: ["tabel perkalian 25", "perkalian 25", "belajar perkalian 25"],
  26: ["tabel perkalian 26", "perkalian 26", "belajar perkalian 26"],
  27: ["tabel perkalian 27", "perkalian 27", "belajar perkalian 27"],
  28: ["tabel perkalian 28", "perkalian 28", "belajar perkalian 28"],
  29: ["tabel perkalian 29", "perkalian 29", "belajar perkalian 29"],
  30: ["tabel perkalian 30", "perkalian 30", "belajar perkalian 30"],
  31: ["tabel perkalian 31", "perkalian 31", "belajar perkalian 31"],
  32: ["tabel perkalian 32", "perkalian 32", "belajar perkalian 32"],
  33: ["tabel perkalian 33", "perkalian 33", "belajar perkalian 33"],
  34: ["tabel perkalian 34", "perkalian 34", "belajar perkalian 34"],
  35: ["tabel perkalian 35", "perkalian 35", "belajar perkalian 35"],
  36: ["tabel perkalian 36", "perkalian 36", "belajar perkalian 36"],
  37: ["tabel perkalian 37", "perkalian 37", "belajar perkalian 37"],
  38: ["tabel perkalian 38", "perkalian 38", "belajar perkalian 38"],
  39: ["tabel perkalian 39", "perkalian 39", "belajar perkalian 39"],
  40: ["tabel perkalian 40", "perkalian 40", "belajar perkalian 40"],
  41: ["tabel perkalian 41", "perkalian 41", "belajar perkalian 41"],
  42: ["tabel perkalian 42", "perkalian 42", "belajar perkalian 42"],
  43: ["tabel perkalian 43", "perkalian 43", "belajar perkalian 43"],
  44: ["tabel perkalian 44", "perkalian 44", "belajar perkalian 44"],
  45: ["tabel perkalian 45", "perkalian 45", "belajar perkalian 45"],
  46: ["tabel perkalian 46", "perkalian 46", "belajar perkalian 46"],
  47: ["tabel perkalian 47", "perkalian 47", "belajar perkalian 47"],
  48: ["tabel perkalian 48", "perkalian 48", "belajar perkalian 48"],
  49: ["tabel perkalian 49", "perkalian 49", "belajar perkalian 49"],
  50: ["tabel perkalian 50", "perkalian 50", "belajar perkalian 50"],
  51: ["tabel perkalian 51", "perkalian 51", "belajar perkalian 51"],
  52: ["tabel perkalian 52", "perkalian 52", "belajar perkalian 52"],
  53: ["tabel perkalian 53", "perkalian 53", "belajar perkalian 53"],
  54: ["tabel perkalian 54", "perkalian 54", "belajar perkalian 54"],
  55: ["tabel perkalian 55", "perkalian 55", "belajar perkalian 55"],
  56: ["tabel perkalian 56", "perkalian 56", "belajar perkalian 56"],
  57: ["tabel perkalian 57", "perkalian 57", "belajar perkalian 57"],
  58: ["tabel perkalian 58", "perkalian 58", "belajar perkalian 58"],
  59: ["tabel perkalian 59", "perkalian 59", "belajar perkalian 59"],
  60: ["tabel perkalian 60", "perkalian 60", "belajar perkalian 60"],
  61: ["tabel perkalian 61", "perkalian 61", "belajar perkalian 61"],
  62: ["tabel perkalian 62", "perkalian 62", "belajar perkalian 62"],
  63: ["tabel perkalian 63", "perkalian 63", "belajar perkalian 63"],
  64: ["tabel perkalian 64", "perkalian 64", "belajar perkalian 64"],
  65: ["tabel perkalian 65", "perkalian 65", "belajar perkalian 65"],
  66: ["tabel perkalian 66", "perkalian 66", "belajar perkalian 66"],
  67: ["tabel perkalian 67", "perkalian 67", "belajar perkalian 67"],
  68: ["tabel perkalian 68", "perkalian 68", "belajar perkalian 68"],
  69: ["tabel perkalian 69", "perkalian 69", "belajar perkalian 69"],
  70: ["tabel perkalian 70", "perkalian 70", "belajar perkalian 70"],
  71: ["tabel perkalian 71", "perkalian 71", "belajar perkalian 71"],
  72: ["tabel perkalian 72", "perkalian 72", "belajar perkalian 72"],
  73: ["tabel perkalian 73", "perkalian 73", "belajar perkalian 73"],
  74: ["tabel perkalian 74", "perkalian 74", "belajar perkalian 74"],
  75: ["tabel perkalian 75", "perkalian 75", "belajar perkalian 75"],
  76: ["tabel perkalian 76", "perkalian 76", "belajar perkalian 76"],
  77: ["tabel perkalian 77", "perkalian 77", "belajar perkalian 77"],
  78: ["tabel perkalian 78", "perkalian 78", "belajar perkalian 78"],
  79: ["tabel perkalian 79", "perkalian 79", "belajar perkalian 79"],
  80: ["tabel perkalian 80", "perkalian 80", "belajar perkalian 80"],
  81: ["tabel perkalian 81", "perkalian 81", "belajar perkalian 81"],
  82: ["tabel perkalian 82", "perkalian 82", "belajar perkalian 82"],
  83: ["tabel perkalian 83", "perkalian 83", "belajar perkalian 83"],
  84: ["tabel perkalian 84", "perkalian 84", "belajar perkalian 84"],
  85: ["tabel perkalian 85", "perkalian 85", "belajar perkalian 85"],
  86: ["tabel perkalian 86", "perkalian 86", "belajar perkalian 86"],
  87: ["tabel perkalian 87", "perkalian 87", "belajar perkalian 87"],
  88: ["tabel perkalian 88", "perkalian 88", "belajar perkalian 88"],
  89: ["tabel perkalian 89", "perkalian 89", "belajar perkalian 89"],
  90: ["tabel perkalian 90", "perkalian 90", "belajar perkalian 90"],
  91: ["tabel perkalian 91", "perkalian 91", "belajar perkalian 91"],
  92: ["tabel perkalian 92", "perkalian 92", "belajar perkalian 92"],
  93: ["tabel perkalian 93", "perkalian 93", "belajar perkalian 93"],
  94: ["tabel perkalian 94", "perkalian 94", "belajar perkalian 94"],
  95: ["tabel perkalian 95", "perkalian 95", "belajar perkalian 95"],
  96: ["tabel perkalian 96", "perkalian 96", "belajar perkalian 96"],
  97: ["tabel perkalian 97", "perkalian 97", "belajar perkalian 97"],
  98: ["tabel perkalian 98", "perkalian 98", "belajar perkalian 98"],
  99: ["tabel perkalian 99", "perkalian 99", "belajar perkalian 99"],
  100: ["tabel perkalian 100", "perkalian 100", "belajar perkalian 100"],
}

export const focusKeywordId = 'tabel perkalian'
