export const numberTitlesPl: Record<number, string> = {
  1: "Tabliczka Mnożenia 1",
  2: "Tabliczka Mnożenia 2",
  3: "Tabliczka Mnożenia 3",
  4: "Tabliczka Mnożenia 4",
  5: "Tabliczka Mnożenia 5",
  6: "Tabliczka Mnożenia 6",
  7: "Tabliczka Mnożenia 7",
  8: "Tabliczka Mnożenia 8",
  9: "Tabliczka Mnożenia 9",
  10: "Tabliczka Mnożenia 10",
  11: "Tabliczka Mnożenia 11",
  12: "Tabliczka Mnożenia 12",
  13: "Tabliczka Mnożenia 13",
  14: "Tabliczka Mnożenia 14",
  15: "Tabliczka Mnożenia 15",
  16: "Tabliczka Mnożenia 16",
  17: "Tabliczka Mnożenia 17",
  18: "Tabliczka Mnożenia 18",
  19: "Tabliczka Mnożenia 19",
  20: "Tabliczka Mnożenia 20",
  21: "Tabliczka Mnożenia 21",
  22: "Tabliczka Mnożenia 22",
  23: "Tabliczka Mnożenia 23",
  24: "Tabliczka Mnożenia 24",
  25: "Tabliczka Mnożenia 25",
  26: "Tabliczka Mnożenia 26",
  27: "Tabliczka Mnożenia 27",
  28: "Tabliczka Mnożenia 28",
  29: "Tabliczka Mnożenia 29",
  30: "Tabliczka Mnożenia 30",
  31: "Tabliczka Mnożenia 31",
  32: "Tabliczka Mnożenia 32",
  33: "Tabliczka Mnożenia 33",
  34: "Tabliczka Mnożenia 34",
  35: "Tabliczka Mnożenia 35",
  36: "Tabliczka Mnożenia 36",
  37: "Tabliczka Mnożenia 37",
  38: "Tabliczka Mnożenia 38",
  39: "Tabliczka Mnożenia 39",
  40: "Tabliczka Mnożenia 40",
  41: "Tabliczka Mnożenia 41",
  42: "Tabliczka Mnożenia 42",
  43: "Tabliczka Mnożenia 43",
  44: "Tabliczka Mnożenia 44",
  45: "Tabliczka Mnożenia 45",
  46: "Tabliczka Mnożenia 46",
  47: "Tabliczka Mnożenia 47",
  48: "Tabliczka Mnożenia 48",
  49: "Tabliczka Mnożenia 49",
  50: "Tabliczka Mnożenia 50",
  51: "Tabliczka Mnożenia 51",
  52: "Tabliczka Mnożenia 52",
  53: "Tabliczka Mnożenia 53",
  54: "Tabliczka Mnożenia 54",
  55: "Tabliczka Mnożenia 55",
  56: "Tabliczka Mnożenia 56",
  57: "Tabliczka Mnożenia 57",
  58: "Tabliczka Mnożenia 58",
  59: "Tabliczka Mnożenia 59",
  60: "Tabliczka Mnożenia 60",
  61: "Tabliczka Mnożenia 61",
  62: "Tabliczka Mnożenia 62",
  63: "Tabliczka Mnożenia 63",
  64: "Tabliczka Mnożenia 64",
  65: "Tabliczka Mnożenia 65",
  66: "Tabliczka Mnożenia 66",
  67: "Tabliczka Mnożenia 67",
  68: "Tabliczka Mnożenia 68",
  69: "Tabliczka Mnożenia 69",
  70: "Tabliczka Mnożenia 70",
  71: "Tabliczka Mnożenia 71",
  72: "Tabliczka Mnożenia 72",
  73: "Tabliczka Mnożenia 73",
  74: "Tabliczka Mnożenia 74",
  75: "Tabliczka Mnożenia 75",
  76: "Tabliczka Mnożenia 76",
  77: "Tabliczka Mnożenia 77",
  78: "Tabliczka Mnożenia 78",
  79: "Tabliczka Mnożenia 79",
  80: "Tabliczka Mnożenia 80",
  81: "Tabliczka Mnożenia 81",
  82: "Tabliczka Mnożenia 82",
  83: "Tabliczka Mnożenia 83",
  84: "Tabliczka Mnożenia 84",
  85: "Tabliczka Mnożenia 85",
  86: "Tabliczka Mnożenia 86",
  87: "Tabliczka Mnożenia 87",
  88: "Tabliczka Mnożenia 88",
  89: "Tabliczka Mnożenia 89",
  90: "Tabliczka Mnożenia 90",
  91: "Tabliczka Mnożenia 91",
  92: "Tabliczka Mnożenia 92",
  93: "Tabliczka Mnożenia 93",
  94: "Tabliczka Mnożenia 94",
  95: "Tabliczka Mnożenia 95",
  96: "Tabliczka Mnożenia 96",
  97: "Tabliczka Mnożenia 97",
  98: "Tabliczka Mnożenia 98",
  99: "Tabliczka Mnożenia 99",
  100: "Tabliczka Mnożenia 100",
}

export const numberDescriptionsPl: Record<number, string> = {
  1: "Tabliczka mnożenia 1: Podstawowa właściwość tożsamości. Dowolna liczba pomnożona przez 1 pozostaje taka sama. Idealna dla początkujących do nauki podstaw mnożenia.",
  2: "Tabliczka mnożenia 2: Ucz się podwajać liczby. Mnożenie przez 2 oznacza dodanie liczby do samej siebie. Doskonała do rozwijania podstawowych umiejętności mnożenia.",
  3: "Tabliczka mnożenia 3: Dodaj liczbę trzy razy. Tabliczka 3 ma piękne wzory cyfr i jest doskonałą pierwszą prawdziwą wyzwaniem w nauce.",
  4: "Tabliczka mnożenia 4: Podwajaj dwukrotnie! Ponieważ 4 = 2 × 2, możesz podwoić liczbę, a następnie podwoić wynik ponownie. Łatwiejsza nauka, gdy znasz tabliczkę 2.",
  5: "Tabliczka mnożenia 5: Łatwy wzór - wszystkie wyniki kończą się na 0 lub 5. Idealna do nauki liczenia pieniędzy i czytania zegara. Jedna z najprostszych tabliczek.",
  6: "Tabliczka mnożenia 6: Pierwsza prawdziwa tabliczka. 6 = 2 × 3, więc możesz pomnożyć przez 2, a następnie przez 3. Ważna dla zaawansowanego mnożenia.",
  7: "Tabliczka mnożenia 7: Wyzwanie! Liczba 7 jest liczbą pierwszą i wymaga regularnej praktyki. Opanowanie jej zwiększa pewność siebie w matematyce.",
  8: "Tabliczka mnożenia 8: Podwajaj trzykrotnie (8 = 2 × 2 × 2). Gdy znasz dobrze tabliczki 2 i 4, ta staje się łatwiejsza. Ważna dla geometrii i muzyki.",
  9: "Tabliczka mnożenia 9: Fascynujące wzory! Suma cyfr w wynikach zawsze dzieli się przez 9. Istnieją również triki z palcami do nauki tej tabliczki.",
  10: "Tabliczka mnożenia 10: Najłatwiejsza! Po prostu dodaj zero na końcu. Podstawa naszego systemu dziesiętnego i punkt odniesienia dla wszystkich tabliczek.",
}

// Add generic descriptions for numbers 11-100
for (let i = 11; i <= 100; i++) {
  numberDescriptionsPl[i] = `Tabliczka mnożenia ${i}: Ucz się mnożyć przez ${i} z interaktywnymi ćwiczeniami, grami i materiałami do druku. Opanuj tabliczkę ${i} dzięki regularnej praktyce i zabawnym metodom nauki.`
}

export const numberSpecialPropertiesPl: Record<number, string> = {
  1: "Właściwość tożsamości",
  2: "Podwajanie",
  3: "Grupowanie po trójkach",
  4: "Podwójne podwojenie",
  5: "Kończy się na 0 lub 5",
  6: "Doskonała liczba",
  7: "Szczęśliwa siódemka",
  8: "Potęga dwójki (2³)",
  9: "Wzór sumy cyfr",
  10: "Właściwość podstawy",
}

export const numberKeywordsPl: Record<number, string[]> = {
  1: ["tabliczka mnożenia 1", "nauka mnożenia", "podstawy mnożenia", "właściwość tożsamości", "mnożenie dla początkujących"],
  2: ["tabliczka mnożenia 2", "podwajanie liczb", "liczby parzyste", "nauka po 2", "podstawowa tabliczka"],
  3: ["tabliczka mnożenia 3", "trójki", "wzór 3-6-9", "nauka po 3", "mnożenie przez trzy"],
  4: ["tabliczka mnożenia 4", "dwukrotne podwajanie", "mnożenie przez cztery", "kwadrat 2", "nauka po 4"],
  5: ["tabliczka mnożenia 5", "nauka po 5", "końce na 0 i 5", "mnożenie przez pięć", "tabliczka do zegara"],
  6: ["tabliczka mnożenia 6", "mnożenie przez sześć", "2×3", "doskonała liczba", "nauka po 6"],
  7: ["tabliczka mnożenia 7", "mnożenie przez siedem", "liczba pierwsza", "trudna tabliczka", "sztuczki z siódemkami"],
  8: ["tabliczka mnożenia 8", "mnożenie przez osiem", "potęga dwójki", "podwajanie 4", "tabliczka 8"],
  9: ["tabliczka mnożenia 9", "mnożenie przez dziewięć", "trik z palcami", "wzór cyfr", "sztuczka z 9"],
  10: ["tabliczka mnożenia 10", "mnożenie przez dziesięć", "dodaj zero", "system dziesiętny", "podstawa 10"],
}

// Add generic keywords for numbers 11-100
for (let i = 11; i <= 100; i++) {
  numberKeywordsPl[i] = [
    `tabliczka mnożenia ${i}`,
    `mnożenie przez ${i}`,
    `nauka tabliczki ${i}`,
    `ćwiczenia z mnożenia ${i}`,
    `tabliczki mnożenia`
  ]
}

export const focusKeywordPl = 'tabliczki mnożenia'
