// Czech metadata for number pages (1-100)

export const numberTitlesCs: Record<number, string> = {
  1: 'Násobilka 1 | Naučte se násobení číslem 1',
  2: 'Násobilka 2 | Naučte se násobení číslem 2',
  3: 'Násobilka 3 | Naučte se násobení číslem 3',
  4: 'Násobilka 4 | Naučte se násobení číslem 4',
  5: 'Násobilka 5 | Naučte se násobení číslem 5',
  6: 'Násobilka 6 - Zábavné hry a praktická cvičení',
  7: 'Násobilka 7 - Zábavné hry a praktická cvičení',
  8: 'Násobilka 8 - Zábavné hry a praktická cvičení',
  9: 'Násobilka 9 - Zábavné hry a praktická cvičení',
  10: 'Násobilka 10 - Zábavné hry a praktická cvičení',
  11: 'Násobilka 11 - Zábavné hry a praktická cvičení',
  12: 'Násobilka 12 - Zábavné hry a praktická cvičení',
  13: 'Násobilka 13 - Zábavné hry a praktická cvičení',
  14: 'Násobilka 14 - Zábavné hry a praktická cvičení',
  15: 'Násobilka 15 - Zábavné hry a praktická cvičení',
  16: 'Násobilka 16 - Zábavné hry a praktická cvičení',
  17: 'Násobilka 17 - Zábavné hry a praktická cvičení',
  18: 'Násobilka 18 - Zábavné hry a praktická cvičení',
  19: 'Násobilka 19 - Zábavné hry a praktická cvičení',
  20: 'Násobilka 20 - Zábavné hry a praktická cvičení',
  21: 'Násobilka 21 | Naučte se násobení číslem 21',
  22: 'Násobilka 22 | Naučte se násobení číslem 22',
  23: 'Násobilka 23 | Naučte se násobení číslem 23',
  24: 'Násobilka 24 | Naučte se násobení číslem 24',
  25: 'Násobilka 25 | Naučte se násobení číslem 25',
  26: 'Násobilka 26 | Naučte se násobení číslem 26',
  27: 'Násobilka 27 | Naučte se násobení číslem 27',
  28: 'Násobilka 28 | Naučte se násobení číslem 28',
  29: 'Násobilka 29 | Naučte se násobení číslem 29',
  30: 'Násobilka 30 | Naučte se násobení číslem 30',
  31: 'Násobilka 31 | Naučte se násobení číslem 31',
  32: 'Násobilka 32 | Naučte se násobení číslem 32',
  33: 'Násobilka 33 | Naučte se násobení číslem 33',
  34: 'Násobilka 34 | Naučte se násobení číslem 34',
  35: 'Násobilka 35 | Naučte se násobení číslem 35',
  36: 'Násobilka 36 | Naučte se násobení číslem 36',
  37: 'Násobilka 37 | Naučte se násobení číslem 37',
  38: 'Násobilka 38 | Naučte se násobení číslem 38',
  39: 'Násobilka 39 | Naučte se násobení číslem 39',
  40: 'Násobilka 40 | Naučte se násobení číslem 40',
  41: 'Násobilka 41 | Naučte se násobení číslem 41',
  42: 'Násobilka 42 | Naučte se násobení číslem 42',
  43: 'Násobilka 43 | Naučte se násobení číslem 43',
  44: 'Násobilka 44 | Naučte se násobení číslem 44',
  45: 'Násobilka 45 | Naučte se násobení číslem 45',
  46: 'Násobilka 46 | Naučte se násobení číslem 46',
  47: 'Násobilka 47 | Naučte se násobení číslem 47',
  48: 'Násobilka 48 | Naučte se násobení číslem 48',
  49: 'Násobilka 49 | Naučte se násobení číslem 49',
  50: 'Násobilka 50 | Naučte se násobení číslem 50',
  51: 'Násobilka 51 | Naučte se násobení číslem 51',
  52: 'Násobilka 52 | Naučte se násobení číslem 52',
  53: 'Násobilka 53 | Naučte se násobení číslem 53',
  54: 'Násobilka 54 | Naučte se násobení číslem 54',
  55: 'Násobilka 55 | Naučte se násobení číslem 55',
  56: 'Násobilka 56 | Naučte se násobení číslem 56',
  57: 'Násobilka 57 | Naučte se násobení číslem 57',
  58: 'Násobilka 58 | Naučte se násobení číslem 58',
  59: 'Násobilka 59 | Naučte se násobení číslem 59',
  60: 'Násobilka 60 | Naučte se násobení číslem 60',
  61: 'Násobilka 61 | Naučte se násobení číslem 61',
  62: 'Násobilka 62 | Naučte se násobení číslem 62',
  63: 'Násobilka 63 | Naučte se násobení číslem 63',
  64: 'Násobilka 64 | Naučte se násobení číslem 64',
  65: 'Násobilka 65 | Naučte se násobení číslem 65',
  66: 'Násobilka 66 | Naučte se násobení číslem 66',
  67: 'Násobilka 67 | Naučte se násobení číslem 67',
  68: 'Násobilka 68 | Naučte se násobení číslem 68',
  69: 'Násobilka 69 | Naučte se násobení číslem 69',
  70: 'Násobilka 70 | Naučte se násobení číslem 70',
  71: 'Násobilka 71 | Naučte se násobení číslem 71',
  72: 'Násobilka 72 | Naučte se násobení číslem 72',
  73: 'Násobilka 73 | Naučte se násobení číslem 73',
  74: 'Násobilka 74 | Naučte se násobení číslem 74',
  75: 'Násobilka 75 | Naučte se násobení číslem 75',
  76: 'Násobilka 76 | Naučte se násobení číslem 76',
  77: 'Násobilka 77 | Naučte se násobení číslem 77',
  78: 'Násobilka 78 | Naučte se násobení číslem 78',
  79: 'Násobilka 79 | Naučte se násobení číslem 79',
  80: 'Násobilka 80 | Naučte se násobení číslem 80',
  81: 'Násobilka 81 | Naučte se násobení číslem 81',
  82: 'Násobilka 82 | Naučte se násobení číslem 82',
  83: 'Násobilka 83 | Naučte se násobení číslem 83',
  84: 'Násobilka 84 | Naučte se násobení číslem 84',
  85: 'Násobilka 85 | Naučte se násobení číslem 85',
  86: 'Násobilka 86 | Naučte se násobení číslem 86',
  87: 'Násobilka 87 | Naučte se násobení číslem 87',
  88: 'Násobilka 88 | Naučte se násobení číslem 88',
  89: 'Násobilka 89 | Naučte se násobení číslem 89',
  90: 'Násobilka 90 | Naučte se násobení číslem 90',
  91: 'Násobilka 91 | Naučte se násobení číslem 91',
  92: 'Násobilka 92 | Naučte se násobení číslem 92',
  93: 'Násobilka 93 | Naučte se násobení číslem 93',
  94: 'Násobilka 94 | Naučte se násobení číslem 94',
  95: 'Násobilka 95 | Naučte se násobení číslem 95',
  96: 'Násobilka 96 | Naučte se násobení číslem 96',
  97: 'Násobilka 97 | Naučte se násobení číslem 97',
  98: 'Násobilka 98 | Naučte se násobení číslem 98',
  99: 'Násobilka 99 | Naučte se násobení číslem 99',
  100: 'Násobilka 100 | Naučte se násobení číslem 100',
}

export const numberDescriptionsCs: Record<number, string> = {
  1: 'Zvládněte násobilku 1. Jasná vysvětlení, vzory a praktické strategie pro pochopení vlastnosti identity a základů násobení.',
  2: 'Zvládněte násobilku 2. Jasná vysvětlení, vzory zdvojování a praktické strategie pro pochopení násobení dvěma.',
  3: 'Zvládněte násobilku 3. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  4: 'Zvládněte násobilku 4. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  5: 'Zvládněte násobilku 5. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  6: 'Zvládněte násobilku 6. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  7: 'Zvládněte násobilku 7. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  8: 'Zvládněte násobilku 8. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  9: 'Zvládněte násobilku 9. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  10: 'Zvládněte násobilku 10. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  11: 'Zvládněte násobilku 11. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  12: 'Zvládněte násobilku 12. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  13: 'Zvládněte násobilku 13. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  14: 'Zvládněte násobilku 14. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  15: 'Zvládněte násobilku 15. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  16: 'Zvládněte násobilku 16. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  17: 'Zvládněte násobilku 17. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  18: 'Zvládněte násobilku 18. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  19: 'Zvládněte násobilku 19. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  20: 'Zvládněte násobilku 20. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  21: 'Zvládněte násobilku 21. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  22: 'Zvládněte násobilku 22. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  23: 'Zvládněte násobilku 23. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  24: 'Zvládněte násobilku 24. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  25: 'Zvládněte násobilku 25. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  26: 'Zvládněte násobilku 26. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  27: 'Zvládněte násobilku 27. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  28: 'Zvládněte násobilku 28. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  29: 'Zvládněte násobilku 29. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  30: 'Zvládněte násobilku 30. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  31: 'Zvládněte násobilku 31. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  32: 'Zvládněte násobilku 32. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  33: 'Zvládněte násobilku 33. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  34: 'Zvládněte násobilku 34. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  35: 'Zvládněte násobilku 35. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  36: 'Zvládněte násobilku 36. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  37: 'Zvládněte násobilku 37. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  38: 'Zvládněte násobilku 38. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  39: 'Zvládněte násobilku 39. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  40: 'Zvládněte násobilku 40. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  41: 'Zvládněte násobilku 41. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  42: 'Zvládněte násobilku 42. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  43: 'Zvládněte násobilku 43. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  44: 'Zvládněte násobilku 44. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  45: 'Zvládněte násobilku 45. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  46: 'Zvládněte násobilku 46. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  47: 'Zvládněte násobilku 47. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  48: 'Zvládněte násobilku 48. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  49: 'Zvládněte násobilku 49. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  50: 'Zvládněte násobilku 50. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  51: 'Zvládněte násobilku 51. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  52: 'Zvládněte násobilku 52. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  53: 'Zvládněte násobilku 53. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  54: 'Zvládněte násobilku 54. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  55: 'Zvládněte násobilku 55. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  56: 'Zvládněte násobilku 56. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  57: 'Zvládněte násobilku 57. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  58: 'Zvládněte násobilku 58. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  59: 'Zvládněte násobilku 59. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  60: 'Zvládněte násobilku 60. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  61: 'Zvládněte násobilku 61. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  62: 'Zvládněte násobilku 62. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  63: 'Zvládněte násobilku 63. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  64: 'Zvládněte násobilku 64. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  65: 'Zvládněte násobilku 65. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  66: 'Zvládněte násobilku 66. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  67: 'Zvládněte násobilku 67. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  68: 'Zvládněte násobilku 68. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  69: 'Zvládněte násobilku 69. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  70: 'Zvládněte násobilku 70. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  71: 'Zvládněte násobilku 71. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  72: 'Zvládněte násobilku 72. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  73: 'Zvládněte násobilku 73. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  74: 'Zvládněte násobilku 74. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  75: 'Zvládněte násobilku 75. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  76: 'Zvládněte násobilku 76. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  77: 'Zvládněte násobilku 77. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  78: 'Zvládněte násobilku 78. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  79: 'Zvládněte násobilku 79. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  80: 'Zvládněte násobilku 80. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  81: 'Zvládněte násobilku 81. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  82: 'Zvládněte násobilku 82. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  83: 'Zvládněte násobilku 83. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  84: 'Zvládněte násobilku 84. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  85: 'Zvládněte násobilku 85. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  86: 'Zvládněte násobilku 86. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  87: 'Zvládněte násobilku 87. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  88: 'Zvládněte násobilku 88. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  89: 'Zvládněte násobilku 89. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  90: 'Zvládněte násobilku 90. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  91: 'Zvládněte násobilku 91. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  92: 'Zvládněte násobilku 92. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  93: 'Zvládněte násobilku 93. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  94: 'Zvládněte násobilku 94. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  95: 'Zvládněte násobilku 95. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  96: 'Zvládněte násobilku 96. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  97: 'Zvládněte násobilku 97. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  98: 'Zvládněte násobilku 98. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  99: 'Zvládněte násobilku 99. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
  100: 'Zvládněte násobilku 100. Jasná vysvětlení, vzory a praktické strategie pro cvičení.',
}

export const numberSpecialPropertiesCs: Record<number, string> = {
  1: 'Vlastnost identity násobení',
  2: 'Sudé číslo, zdvojení',
  3: 'Liché číslo, trojúhelníkový vzor',
  4: 'Sudé číslo, druhá mocnina (2×2)',
  5: 'Liché číslo, polovina z 10',
  6: 'Sudé číslo, dokonalé číslo',
  7: 'Liché číslo, prvočíslo',
  8: 'Sudé číslo, třetí mocnina (2³)',
  9: 'Liché číslo, druhá mocnina (3×3)',
  10: 'Sudé číslo, základ desítkové soustavy',
  11: 'Liché číslo, prvočíslo, palindromický vzor',
  12: 'Sudé číslo, vysoce složené číslo',
  13: 'Liché číslo, prvočíslo',
  14: 'Sudé číslo, 2×7',
  15: 'Liché číslo, 3×5',
  16: 'Sudé číslo, druhá mocnina (4×4)',
  17: 'Liché číslo, prvočíslo',
  18: 'Sudé číslo, 2×9',
  19: 'Liché číslo, prvočíslo',
  20: 'Sudé číslo, 2×10',
  21: 'Liché číslo, 3×7',
  22: 'Sudé číslo, 2×11',
  23: 'Liché číslo, prvočíslo',
  24: 'Sudé číslo, vysoce složené číslo',
  25: 'Liché číslo, druhá mocnina (5×5)',
  26: 'Sudé číslo, 2×13',
  27: 'Liché číslo, třetí mocnina (3³)',
  28: 'Sudé číslo, dokonalé číslo',
  29: 'Liché číslo, prvočíslo',
  30: 'Sudé číslo, 3×10',
  31: 'Liché číslo, prvočíslo',
  32: 'Sudé číslo, 2⁵',
  33: 'Liché číslo, 3×11',
  34: 'Sudé číslo, 2×17',
  35: 'Liché číslo, 5×7',
  36: 'Sudé číslo, druhá mocnina (6×6)',
  37: 'Liché číslo, prvočíslo',
  38: 'Sudé číslo, 2×19',
  39: 'Liché číslo, 3×13',
  40: 'Sudé číslo, 4×10',
  41: 'Liché číslo, prvočíslo',
  42: 'Sudé číslo, 6×7',
  43: 'Liché číslo, prvočíslo',
  44: 'Sudé číslo, 4×11',
  45: 'Liché číslo, 5×9',
  46: 'Sudé číslo, 2×23',
  47: 'Liché číslo, prvočíslo',
  48: 'Sudé číslo, vysoce složené číslo',
  49: 'Liché číslo, druhá mocnina (7×7)',
  50: 'Sudé číslo, polovina stovky',
  51: 'Liché číslo, 3×17',
  52: 'Sudé číslo, 4×13',
  53: 'Liché číslo, prvočíslo',
  54: 'Sudé číslo, 6×9',
  55: 'Liché číslo, 5×11',
  56: 'Sudé číslo, 7×8',
  57: 'Liché číslo, 3×19',
  58: 'Sudé číslo, 2×29',
  59: 'Liché číslo, prvočíslo',
  60: 'Sudé číslo, vysoce složené číslo',
  61: 'Liché číslo, prvočíslo',
  62: 'Sudé číslo, 2×31',
  63: 'Liché číslo, 7×9',
  64: 'Sudé číslo, druhá mocnina (8×8), třetí mocnina (4³)',
  65: 'Liché číslo, 5×13',
  66: 'Sudé číslo, 6×11',
  67: 'Liché číslo, prvočíslo',
  68: 'Sudé číslo, 4×17',
  69: 'Liché číslo, 3×23',
  70: 'Sudé číslo, 7×10',
  71: 'Liché číslo, prvočíslo',
  72: 'Sudé číslo, vysoce složené číslo',
  73: 'Liché číslo, prvočíslo',
  74: 'Sudé číslo, 2×37',
  75: 'Liché číslo, 3×25',
  76: 'Sudé číslo, 4×19',
  77: 'Liché číslo, 7×11',
  78: 'Sudé číslo, 6×13',
  79: 'Liché číslo, prvočíslo',
  80: 'Sudé číslo, 8×10',
  81: 'Liché číslo, druhá mocnina (9×9)',
  82: 'Sudé číslo, 2×41',
  83: 'Liché číslo, prvočíslo',
  84: 'Sudé číslo, 7×12',
  85: 'Liché číslo, 5×17',
  86: 'Sudé číslo, 2×43',
  87: 'Liché číslo, 3×29',
  88: 'Sudé číslo, 8×11',
  89: 'Liché číslo, prvočíslo',
  90: 'Sudé číslo, 9×10',
  91: 'Liché číslo, 7×13',
  92: 'Sudé číslo, 4×23',
  93: 'Liché číslo, 3×31',
  94: 'Sudé číslo, 2×47',
  95: 'Liché číslo, 5×19',
  96: 'Sudé číslo, vysoce složené číslo',
  97: 'Liché číslo, prvočíslo',
  98: 'Sudé číslo, 2×49',
  99: 'Liché číslo, 9×11',
  100: 'Sudé číslo, druhá mocnina (10×10), milník',
}
